// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xlfcw1a2_bbox.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XLfcw1a2_bbox_CfgInitialize(XLfcw1a2_bbox *InstancePtr, XLfcw1a2_bbox_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XLfcw1a2_bbox_Start(XLfcw1a2_bbox *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_AP_CTRL) & 0x80;
    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XLfcw1a2_bbox_IsDone(XLfcw1a2_bbox *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XLfcw1a2_bbox_IsIdle(XLfcw1a2_bbox *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XLfcw1a2_bbox_IsReady(XLfcw1a2_bbox *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XLfcw1a2_bbox_EnableAutoRestart(XLfcw1a2_bbox *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_AP_CTRL, 0x80);
}

void XLfcw1a2_bbox_DisableAutoRestart(XLfcw1a2_bbox *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_AP_CTRL, 0);
}

void XLfcw1a2_bbox_Set_in_V(XLfcw1a2_bbox *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_IN_V_DATA, (u32)(Data));
    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_IN_V_DATA + 4, (u32)(Data >> 32));
}

u64 XLfcw1a2_bbox_Get_in_V(XLfcw1a2_bbox *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_IN_V_DATA);
    Data += (u64)XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_IN_V_DATA + 4) << 32;
    return Data;
}

void XLfcw1a2_bbox_Set_out_V(XLfcw1a2_bbox *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_OUT_V_DATA, (u32)(Data));
    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_OUT_V_DATA + 4, (u32)(Data >> 32));
}

u64 XLfcw1a2_bbox_Get_out_V(XLfcw1a2_bbox *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_OUT_V_DATA);
    Data += (u64)XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_OUT_V_DATA + 4) << 32;
    return Data;
}

void XLfcw1a2_bbox_Set_doInit(XLfcw1a2_bbox *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_DOINIT_DATA, Data);
}

u32 XLfcw1a2_bbox_Get_doInit(XLfcw1a2_bbox *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_DOINIT_DATA);
    return Data;
}

void XLfcw1a2_bbox_Set_targetLayer(XLfcw1a2_bbox *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_TARGETLAYER_DATA, Data);
}

u32 XLfcw1a2_bbox_Get_targetLayer(XLfcw1a2_bbox *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_TARGETLAYER_DATA);
    return Data;
}

void XLfcw1a2_bbox_Set_targetMem(XLfcw1a2_bbox *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_TARGETMEM_DATA, Data);
}

u32 XLfcw1a2_bbox_Get_targetMem(XLfcw1a2_bbox *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_TARGETMEM_DATA);
    return Data;
}

void XLfcw1a2_bbox_Set_targetInd(XLfcw1a2_bbox *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_TARGETIND_DATA, Data);
}

u32 XLfcw1a2_bbox_Get_targetInd(XLfcw1a2_bbox *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_TARGETIND_DATA);
    return Data;
}

void XLfcw1a2_bbox_Set_targetThresh(XLfcw1a2_bbox *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_TARGETTHRESH_DATA, Data);
}

u32 XLfcw1a2_bbox_Get_targetThresh(XLfcw1a2_bbox *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_TARGETTHRESH_DATA);
    return Data;
}

void XLfcw1a2_bbox_Set_val_V(XLfcw1a2_bbox *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_VAL_V_DATA, (u32)(Data));
    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_VAL_V_DATA + 4, (u32)(Data >> 32));
}

u64 XLfcw1a2_bbox_Get_val_V(XLfcw1a2_bbox *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_VAL_V_DATA);
    Data += (u64)XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_VAL_V_DATA + 4) << 32;
    return Data;
}

void XLfcw1a2_bbox_Set_numReps(XLfcw1a2_bbox *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_NUMREPS_DATA, Data);
}

u32 XLfcw1a2_bbox_Get_numReps(XLfcw1a2_bbox *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_NUMREPS_DATA);
    return Data;
}

void XLfcw1a2_bbox_InterruptGlobalEnable(XLfcw1a2_bbox *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_GIE, 1);
}

void XLfcw1a2_bbox_InterruptGlobalDisable(XLfcw1a2_bbox *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_GIE, 0);
}

void XLfcw1a2_bbox_InterruptEnable(XLfcw1a2_bbox *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_IER);
    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_IER, Register | Mask);
}

void XLfcw1a2_bbox_InterruptDisable(XLfcw1a2_bbox *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_IER);
    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_IER, Register & (~Mask));
}

void XLfcw1a2_bbox_InterruptClear(XLfcw1a2_bbox *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XLfcw1a2_bbox_WriteReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_ISR, Mask);
}

u32 XLfcw1a2_bbox_InterruptGetEnabled(XLfcw1a2_bbox *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_IER);
}

u32 XLfcw1a2_bbox_InterruptGetStatus(XLfcw1a2_bbox *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XLfcw1a2_bbox_ReadReg(InstancePtr->Control_BaseAddress, XLFCW1A2_BBOX_CONTROL_ADDR_ISR);
}

