# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/bnn_imports/ultra96.xdc

# Block Designs: bd/procsys/procsys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==procsys || ORIG_REF_NAME==procsys} -quiet] -quiet

# IP: bd/procsys/ip/procsys_zynq_ultra_ps_e_0_0/procsys_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==procsys_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==procsys_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/procsys/ip/procsys_ps8_0_axi_periph_0/procsys_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==procsys_ps8_0_axi_periph_0 || ORIG_REF_NAME==procsys_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/procsys/ip/procsys_rst_ps8_0_299M_0/procsys_rst_ps8_0_299M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==procsys_rst_ps8_0_299M_0 || ORIG_REF_NAME==procsys_rst_ps8_0_299M_0} -quiet] -quiet

# IP: bd/procsys/ip/procsys_axi_smc_0/procsys_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==procsys_axi_smc_0 || ORIG_REF_NAME==procsys_axi_smc_0} -quiet] -quiet

# IP: bd/procsys/ip/procsys_auto_ds_0/procsys_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==procsys_auto_ds_0 || ORIG_REF_NAME==procsys_auto_ds_0} -quiet] -quiet

# IP: bd/procsys/ip/procsys_auto_pc_0/procsys_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==procsys_auto_pc_0 || ORIG_REF_NAME==procsys_auto_pc_0} -quiet] -quiet

# XDC: bd/procsys/procsys_ooc.xdc
