// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ConvolutionInputGene_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_V_V_dout,
        in_V_V_empty_n,
        in_V_V_read,
        out_V_V_din,
        out_V_V_full_n,
        out_V_V_write,
        numReps_dout,
        numReps_empty_n,
        numReps_read,
        numReps_out_din,
        numReps_out_full_n,
        numReps_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state6 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] in_V_V_dout;
input   in_V_V_empty_n;
output   in_V_V_read;
output  [23:0] out_V_V_din;
input   out_V_V_full_n;
output   out_V_V_write;
input  [31:0] numReps_dout;
input   numReps_empty_n;
output   numReps_read;
output  [31:0] numReps_out_din;
input   numReps_out_full_n;
output   numReps_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_read;
reg out_V_V_write;
reg numReps_read;
reg numReps_out_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_V_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_i_2864_reg_1001;
reg   [0:0] or_cond_i_reg_1046;
reg    out_V_V_blk_n;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] tmp_i_2864_reg_1001_pp0_iter2_reg;
reg   [0:0] tmp_111_i_reg_1005;
reg   [0:0] tmp_111_i_reg_1005_pp0_iter2_reg;
reg    numReps_blk_n;
reg    numReps_out_blk_n;
reg   [45:0] indvar_flatten_reg_305;
reg   [13:0] i_i_reg_316;
reg   [31:0] reg_394;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_predicate_op170_read_state4;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_predicate_op219_write_state5;
reg    ap_block_state5_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_i_2864_fu_497_p2;
wire   [0:0] or_cond_i_fu_685_p2;
wire   [45:0] bound_fu_422_p2;
reg   [45:0] bound_reg_977;
reg    ap_block_state1;
wire   [0:0] exitcond_flatten_fu_448_p2;
reg   [0:0] exitcond_flatten_reg_982;
wire   [45:0] indvar_flatten_next_fu_453_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] tmp_i_fu_459_p2;
reg   [0:0] tmp_i_reg_991;
wire   [13:0] i_fu_471_p3;
wire   [0:0] tmp_111_i_fu_506_p2;
wire   [1:0] tmp_2999_fu_524_p1;
reg   [1:0] tmp_2999_reg_1009;
wire   [0:0] tmp_124_i_fu_376_p2;
reg   [0:0] tmp_124_i_reg_1050;
wire   [0:0] tmp_115_i_fu_382_p2;
reg   [0:0] tmp_115_i_reg_1055;
wire   [23:0] outElem_V_fu_797_p6;
reg   [23:0] outElem_V_reg_1059;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
wire   [4:0] inputBuf_0_V_address0;
reg    inputBuf_0_V_ce0;
wire   [23:0] inputBuf_0_V_q0;
reg   [4:0] inputBuf_0_V_address1;
reg    inputBuf_0_V_ce1;
reg    inputBuf_0_V_we1;
wire   [4:0] inputBuf_1_V_address0;
reg    inputBuf_1_V_ce0;
wire   [23:0] inputBuf_1_V_q0;
reg   [4:0] inputBuf_1_V_address1;
reg    inputBuf_1_V_ce1;
reg    inputBuf_1_V_we1;
wire   [4:0] inputBuf_2_V_address0;
reg    inputBuf_2_V_ce0;
wire   [23:0] inputBuf_2_V_q0;
reg   [4:0] inputBuf_2_V_address1;
reg    inputBuf_2_V_ce1;
reg    inputBuf_2_V_we1;
wire   [4:0] inputBuf_3_V_address0;
reg    inputBuf_3_V_ce0;
wire   [23:0] inputBuf_3_V_q0;
reg   [4:0] inputBuf_3_V_address1;
reg    inputBuf_3_V_ce1;
reg    inputBuf_3_V_we1;
wire   [63:0] tmp_113_i_fu_546_p1;
wire   [63:0] tmp_123_i_fu_811_p1;
wire   [63:0] tmp_110_i_fu_858_p1;
reg    ap_block_pp0_stage0_01001;
reg   [31:0] read_block_5_fu_98;
wire   [31:0] read_block_1_i_mid2_fu_485_p3;
wire   [31:0] read_block_3_cast_i_fu_713_p1;
wire   [31:0] read_block_fu_771_p2;
reg   [31:0] ofm_y_1_i_fu_102;
wire   [31:0] p_ofm_y_4_i_fu_642_p3;
wire   [0:0] tmp_114_i_fu_560_p2;
wire   [0:0] tmp_116_i_fu_577_p2;
wire   [0:0] tmp_118_i_fu_588_p2;
wire   [0:0] tmp_119_i_fu_608_p2;
reg   [31:0] ofm_x_4_fu_106;
wire   [31:0] ofm_x_fu_602_p2;
reg   [31:0] k_y_4_fu_110;
wire   [31:0] k_y_fu_528_p2;
reg   [31:0] inp_4_fu_114;
wire   [31:0] p_inp_1_i_fu_634_p3;
wire   [31:0] inp_fu_755_p2;
reg   [31:0] k_x_4_fu_118;
wire   [31:0] k_x_fu_571_p2;
reg   [31:0] count_simd_4_fu_122;
wire   [31:0] count_simd_fu_554_p2;
reg   [31:0] current_block_write_17_fu_126;
wire   [31:0] current_block_write_10_fu_846_p3;
wire   [31:0] current_block_write_7_fu_882_p3;
reg   [31:0] current_line_5_fu_130;
wire   [31:0] current_line_3_i_fu_697_p3;
wire   [31:0] grp_fu_370_p2;
reg   [31:0] counter_internal_blo_fu_134;
wire   [31:0] p_i_fu_742_p3;
wire   [1:0] tmp_3002_fu_819_p1;
wire   [1:0] tmp_2998_fu_866_p1;
wire   [44:0] tmp_s_fu_398_p3;
wire   [33:0] tmp_17_fu_410_p3;
wire   [45:0] p_shl_fu_406_p1;
wire   [45:0] p_shl2_fu_418_p1;
wire   [13:0] i_i_op_fu_465_p2;
wire   [31:0] tmp_fu_534_p2;
wire   [31:0] current_line_in_bloc_fu_540_p2;
wire   [31:0] ofm_y_fu_622_p2;
wire   [0:0] tmp_120_i_fu_628_p2;
wire   [26:0] tmp_3001_fu_669_p4;
wire   [0:0] tmp_121_i_fu_663_p2;
wire   [0:0] icmp_fu_679_p2;
wire   [5:0] tmp_2997_fu_493_p1;
wire   [5:0] read_block_3_cast_fu_691_p2;
wire   [5:0] read_block_3_fu_705_p3;
wire   [31:0] counter_internal_blo_16_fu_730_p2;
wire   [0:0] tmp_126_i_fu_736_p2;
wire   [1:0] tmp_3000_fu_782_p1;
wire   [1:0] tmp1_fu_786_p2;
wire   [1:0] outElem_V_fu_797_p5;
wire   [31:0] current_block_write_8_fu_826_p2;
wire   [0:0] tmp_125_i_fu_832_p2;
wire   [31:0] current_block_write_9_fu_838_p3;
wire   [31:0] current_block_write_fu_870_p2;
wire   [0:0] tmp_117_i_fu_876_p2;
wire    ap_CS_fsm_state6;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_397;
reg    ap_condition_409;
reg    ap_condition_420;
reg    ap_condition_431;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

ConvolutionInputGbkb #(
    .DataWidth( 24 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
inputBuf_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_0_V_address0),
    .ce0(inputBuf_0_V_ce0),
    .q0(inputBuf_0_V_q0),
    .address1(inputBuf_0_V_address1),
    .ce1(inputBuf_0_V_ce1),
    .we1(inputBuf_0_V_we1),
    .d1(in_V_V_dout)
);

ConvolutionInputGbkb #(
    .DataWidth( 24 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
inputBuf_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_1_V_address0),
    .ce0(inputBuf_1_V_ce0),
    .q0(inputBuf_1_V_q0),
    .address1(inputBuf_1_V_address1),
    .ce1(inputBuf_1_V_ce1),
    .we1(inputBuf_1_V_we1),
    .d1(in_V_V_dout)
);

ConvolutionInputGbkb #(
    .DataWidth( 24 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
inputBuf_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_2_V_address0),
    .ce0(inputBuf_2_V_ce0),
    .q0(inputBuf_2_V_q0),
    .address1(inputBuf_2_V_address1),
    .ce1(inputBuf_2_V_ce1),
    .we1(inputBuf_2_V_we1),
    .d1(in_V_V_dout)
);

ConvolutionInputGbkb #(
    .DataWidth( 24 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
inputBuf_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_3_V_address0),
    .ce0(inputBuf_3_V_ce0),
    .q0(inputBuf_3_V_q0),
    .address1(inputBuf_3_V_address1),
    .ce1(inputBuf_3_V_ce1),
    .we1(inputBuf_3_V_we1),
    .d1(in_V_V_dout)
);

BBJ_u96_cnvW1A1_mfYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .din2_WIDTH( 24 ),
    .din3_WIDTH( 24 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 24 ))
BBJ_u96_cnvW1A1_mfYi_U33(
    .din0(inputBuf_0_V_q0),
    .din1(inputBuf_1_V_q0),
    .din2(inputBuf_2_V_q0),
    .din3(inputBuf_3_V_q0),
    .din4(outElem_V_fu_797_p5),
    .dout(outElem_V_fu_797_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_114_i_fu_560_p2 == 1'd0) & (tmp_i_2864_fu_497_p2 == 1'd0) & (tmp_111_i_fu_506_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        count_simd_4_fu_122 <= count_simd_fu_554_p2;
    end else if ((((tmp_116_i_fu_577_p2 == 1'd0) & (tmp_i_2864_fu_497_p2 == 1'd0) & (tmp_114_i_fu_560_p2 == 1'd1) & (tmp_111_i_fu_506_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_118_i_fu_588_p2 == 1'd0) & (tmp_i_2864_fu_497_p2 == 1'd0) & (tmp_116_i_fu_577_p2 == 1'd1) & (tmp_114_i_fu_560_p2 == 1'd1) & (tmp_111_i_fu_506_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_119_i_fu_608_p2 == 1'd0) & (tmp_i_2864_fu_497_p2 == 1'd0) & (tmp_118_i_fu_588_p2 == 1'd1) & (tmp_116_i_fu_577_p2 == 1'd1) & (tmp_114_i_fu_560_p2 == 1'd1) & (tmp_111_i_fu_506_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2864_fu_497_p2 == 1'd0) & (tmp_119_i_fu_608_p2 == 1'd1) & (tmp_118_i_fu_588_p2 == 1'd1) & (tmp_116_i_fu_577_p2 == 1'd1) & (tmp_114_i_fu_560_p2 == 1'd1) & (tmp_111_i_fu_506_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        count_simd_4_fu_122 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2864_fu_497_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        counter_internal_blo_fu_134 <= p_i_fu_742_p3;
    end else if ((((tmp_115_i_fu_382_p2 == 1'd1) & (tmp_i_2864_fu_497_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        counter_internal_blo_fu_134 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_115_i_reg_1055 == 1'd1) & (tmp_i_2864_reg_1001 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_block_write_17_fu_126 <= current_block_write_7_fu_882_p3;
    end else if (((or_cond_i_reg_1046 == 1'd1) & (tmp_i_2864_reg_1001 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_block_write_17_fu_126 <= current_block_write_10_fu_846_p3;
    end else if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        current_block_write_17_fu_126 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_115_i_fu_382_p2 == 1'd0) & (tmp_i_2864_fu_497_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_line_5_fu_130 <= grp_fu_370_p2;
    end else if (((tmp_i_2864_fu_497_p2 == 1'd0) & (or_cond_i_fu_685_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_line_5_fu_130 <= current_line_3_i_fu_697_p3;
    end else if ((((tmp_115_i_fu_382_p2 == 1'd1) & (tmp_i_2864_fu_497_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        current_line_5_fu_130 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_448_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_i_reg_316 <= i_fu_471_p3;
    end else if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_i_reg_316 <= 14'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_448_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_reg_305 <= indvar_flatten_next_fu_453_p2;
    end else if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_305 <= 46'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2864_fu_497_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inp_4_fu_114 <= inp_fu_755_p2;
    end else if (((tmp_i_2864_fu_497_p2 == 1'd0) & (tmp_119_i_fu_608_p2 == 1'd1) & (tmp_118_i_fu_588_p2 == 1'd1) & (tmp_116_i_fu_577_p2 == 1'd1) & (tmp_114_i_fu_560_p2 == 1'd1) & (tmp_111_i_fu_506_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inp_4_fu_114 <= p_inp_1_i_fu_634_p3;
    end else if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        inp_4_fu_114 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_116_i_fu_577_p2 == 1'd0) & (tmp_i_2864_fu_497_p2 == 1'd0) & (tmp_114_i_fu_560_p2 == 1'd1) & (tmp_111_i_fu_506_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_x_4_fu_118 <= k_x_fu_571_p2;
    end else if ((((tmp_118_i_fu_588_p2 == 1'd0) & (tmp_i_2864_fu_497_p2 == 1'd0) & (tmp_116_i_fu_577_p2 == 1'd1) & (tmp_114_i_fu_560_p2 == 1'd1) & (tmp_111_i_fu_506_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_119_i_fu_608_p2 == 1'd0) & (tmp_i_2864_fu_497_p2 == 1'd0) & (tmp_118_i_fu_588_p2 == 1'd1) & (tmp_116_i_fu_577_p2 == 1'd1) & (tmp_114_i_fu_560_p2 == 1'd1) & (tmp_111_i_fu_506_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2864_fu_497_p2 == 1'd0) & (tmp_119_i_fu_608_p2 == 1'd1) & (tmp_118_i_fu_588_p2 == 1'd1) & (tmp_116_i_fu_577_p2 == 1'd1) & (tmp_114_i_fu_560_p2 == 1'd1) & (tmp_111_i_fu_506_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        k_x_4_fu_118 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_118_i_fu_588_p2 == 1'd0) & (tmp_i_2864_fu_497_p2 == 1'd0) & (tmp_116_i_fu_577_p2 == 1'd1) & (tmp_114_i_fu_560_p2 == 1'd1) & (tmp_111_i_fu_506_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_y_4_fu_110 <= k_y_fu_528_p2;
    end else if ((((tmp_i_2864_fu_497_p2 == 1'd0) & (tmp_118_i_fu_588_p2 == 1'd1) & (tmp_116_i_fu_577_p2 == 1'd1) & (tmp_114_i_fu_560_p2 == 1'd1) & (tmp_111_i_fu_506_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        k_y_4_fu_110 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_119_i_fu_608_p2 == 1'd0) & (tmp_i_2864_fu_497_p2 == 1'd0) & (tmp_118_i_fu_588_p2 == 1'd1) & (tmp_116_i_fu_577_p2 == 1'd1) & (tmp_114_i_fu_560_p2 == 1'd1) & (tmp_111_i_fu_506_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ofm_x_4_fu_106 <= ofm_x_fu_602_p2;
    end else if ((((tmp_i_2864_fu_497_p2 == 1'd0) & (tmp_119_i_fu_608_p2 == 1'd1) & (tmp_118_i_fu_588_p2 == 1'd1) & (tmp_116_i_fu_577_p2 == 1'd1) & (tmp_114_i_fu_560_p2 == 1'd1) & (tmp_111_i_fu_506_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        ofm_x_4_fu_106 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2864_fu_497_p2 == 1'd0) & (tmp_119_i_fu_608_p2 == 1'd1) & (tmp_118_i_fu_588_p2 == 1'd1) & (tmp_116_i_fu_577_p2 == 1'd1) & (tmp_114_i_fu_560_p2 == 1'd1) & (tmp_111_i_fu_506_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ofm_y_1_i_fu_102 <= p_ofm_y_4_i_fu_642_p3;
    end else if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ofm_y_1_i_fu_102 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_115_i_fu_382_p2 == 1'd1) & (tmp_i_2864_fu_497_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        read_block_5_fu_98 <= read_block_fu_771_p2;
    end else if (((tmp_i_2864_fu_497_p2 == 1'd0) & (or_cond_i_fu_685_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        read_block_5_fu_98 <= read_block_3_cast_i_fu_713_p1;
    end else if ((((tmp_115_i_fu_382_p2 == 1'd0) & (tmp_i_2864_fu_497_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((or_cond_i_fu_685_p2 == 1'd0) & (tmp_i_2864_fu_497_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        read_block_5_fu_98 <= read_block_1_i_mid2_fu_485_p3;
    end else if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        read_block_5_fu_98 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bound_reg_977[45 : 2] <= bound_fu_422_p2[45 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond_flatten_reg_982 <= exitcond_flatten_fu_448_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2864_fu_497_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_cond_i_reg_1046 <= or_cond_i_fu_685_p2;
        tmp_111_i_reg_1005 <= tmp_111_i_fu_506_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_111_i_reg_1005 == 1'd1) & (tmp_i_2864_reg_1001 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outElem_V_reg_1059 <= outElem_V_fu_797_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((((tmp_i_2864_fu_497_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2864_fu_497_p2 == 1'd0) & (or_cond_i_fu_685_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_394 <= current_line_5_fu_130;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        tmp_111_i_reg_1005_pp0_iter2_reg <= tmp_111_i_reg_1005;
        tmp_i_2864_reg_1001_pp0_iter2_reg <= tmp_i_2864_reg_1001;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2864_fu_497_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_115_i_reg_1055 <= tmp_115_i_fu_382_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2864_fu_497_p2 == 1'd0) & (or_cond_i_fu_685_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_124_i_reg_1050 <= tmp_124_i_fu_376_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_2864_fu_497_p2 == 1'd0) & (tmp_111_i_fu_506_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_2999_reg_1009 <= tmp_2999_fu_524_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_982 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_i_2864_reg_1001 <= tmp_i_2864_fu_497_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_448_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_i_reg_991 <= tmp_i_fu_459_p2;
    end
end

always @ (*) begin
    if ((exitcond_flatten_fu_448_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1046 == 1'd1) & (tmp_i_2864_reg_1001 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_i_2864_reg_1001 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        in_V_V_blk_n = in_V_V_empty_n;
    end else begin
        in_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op170_read_state4 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2864_reg_1001 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        in_V_V_read = 1'b1;
    end else begin
        in_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((tmp_i_2864_reg_1001 == 1'd1) & (tmp_2998_fu_866_p1 == 2'd0))) begin
            inputBuf_0_V_address1 = tmp_110_i_fu_858_p1;
        end else if ((1'b1 == ap_condition_397)) begin
            inputBuf_0_V_address1 = tmp_123_i_fu_811_p1;
        end else begin
            inputBuf_0_V_address1 = 'bx;
        end
    end else begin
        inputBuf_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_0_V_ce0 = 1'b1;
    end else begin
        inputBuf_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1046 == 1'd1) & (tmp_i_2864_reg_1001 == 1'd0) & (tmp_3002_fu_819_p1 == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2864_reg_1001 == 1'd1) & (tmp_2998_fu_866_p1 == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_0_V_ce1 = 1'b1;
    end else begin
        inputBuf_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1046 == 1'd1) & (tmp_i_2864_reg_1001 == 1'd0) & (tmp_3002_fu_819_p1 == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2864_reg_1001 == 1'd1) & (tmp_2998_fu_866_p1 == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_0_V_we1 = 1'b1;
    end else begin
        inputBuf_0_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((tmp_i_2864_reg_1001 == 1'd1) & (tmp_2998_fu_866_p1 == 2'd1))) begin
            inputBuf_1_V_address1 = tmp_110_i_fu_858_p1;
        end else if ((1'b1 == ap_condition_409)) begin
            inputBuf_1_V_address1 = tmp_123_i_fu_811_p1;
        end else begin
            inputBuf_1_V_address1 = 'bx;
        end
    end else begin
        inputBuf_1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_1_V_ce0 = 1'b1;
    end else begin
        inputBuf_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1046 == 1'd1) & (tmp_i_2864_reg_1001 == 1'd0) & (tmp_3002_fu_819_p1 == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2864_reg_1001 == 1'd1) & (tmp_2998_fu_866_p1 == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_1_V_ce1 = 1'b1;
    end else begin
        inputBuf_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1046 == 1'd1) & (tmp_i_2864_reg_1001 == 1'd0) & (tmp_3002_fu_819_p1 == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2864_reg_1001 == 1'd1) & (tmp_2998_fu_866_p1 == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_1_V_we1 = 1'b1;
    end else begin
        inputBuf_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((tmp_i_2864_reg_1001 == 1'd1) & (tmp_2998_fu_866_p1 == 2'd2))) begin
            inputBuf_2_V_address1 = tmp_110_i_fu_858_p1;
        end else if ((1'b1 == ap_condition_420)) begin
            inputBuf_2_V_address1 = tmp_123_i_fu_811_p1;
        end else begin
            inputBuf_2_V_address1 = 'bx;
        end
    end else begin
        inputBuf_2_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_2_V_ce0 = 1'b1;
    end else begin
        inputBuf_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1046 == 1'd1) & (tmp_i_2864_reg_1001 == 1'd0) & (tmp_3002_fu_819_p1 == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2864_reg_1001 == 1'd1) & (tmp_2998_fu_866_p1 == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_2_V_ce1 = 1'b1;
    end else begin
        inputBuf_2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1046 == 1'd1) & (tmp_i_2864_reg_1001 == 1'd0) & (tmp_3002_fu_819_p1 == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2864_reg_1001 == 1'd1) & (tmp_2998_fu_866_p1 == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_2_V_we1 = 1'b1;
    end else begin
        inputBuf_2_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((tmp_i_2864_reg_1001 == 1'd1) & (tmp_2998_fu_866_p1 == 2'd3))) begin
            inputBuf_3_V_address1 = tmp_110_i_fu_858_p1;
        end else if ((1'b1 == ap_condition_431)) begin
            inputBuf_3_V_address1 = tmp_123_i_fu_811_p1;
        end else begin
            inputBuf_3_V_address1 = 'bx;
        end
    end else begin
        inputBuf_3_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_3_V_ce0 = 1'b1;
    end else begin
        inputBuf_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1046 == 1'd1) & (tmp_i_2864_reg_1001 == 1'd0) & (tmp_3002_fu_819_p1 == 2'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2864_reg_1001 == 1'd1) & (tmp_2998_fu_866_p1 == 2'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_3_V_ce1 = 1'b1;
    end else begin
        inputBuf_3_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1046 == 1'd1) & (tmp_i_2864_reg_1001 == 1'd0) & (tmp_3002_fu_819_p1 == 2'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_2864_reg_1001 == 1'd1) & (tmp_2998_fu_866_p1 == 2'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_3_V_we1 = 1'b1;
    end else begin
        inputBuf_3_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_blk_n = numReps_empty_n;
    end else begin
        numReps_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_out_blk_n = numReps_out_full_n;
    end else begin
        numReps_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_out_write = 1'b1;
    end else begin
        numReps_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_read = 1'b1;
    end else begin
        numReps_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_2864_reg_1001_pp0_iter2_reg == 1'd0) & (tmp_111_i_reg_1005_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        out_V_V_blk_n = out_V_V_full_n;
    end else begin
        out_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op219_write_state5 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_V_V_write = 1'b1;
    end else begin
        out_V_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (exitcond_flatten_fu_448_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (exitcond_flatten_fu_448_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((out_V_V_full_n == 1'b0) & (ap_predicate_op219_write_state5 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((in_V_V_empty_n == 1'b0) & (ap_predicate_op170_read_state4 == 1'b1)) | ((tmp_i_2864_reg_1001 == 1'd1) & (in_V_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((out_V_V_full_n == 1'b0) & (ap_predicate_op219_write_state5 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((in_V_V_empty_n == 1'b0) & (ap_predicate_op170_read_state4 == 1'b1)) | ((tmp_i_2864_reg_1001 == 1'd1) & (in_V_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((out_V_V_full_n == 1'b0) & (ap_predicate_op219_write_state5 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((in_V_V_empty_n == 1'b0) & (ap_predicate_op170_read_state4 == 1'b1)) | ((tmp_i_2864_reg_1001 == 1'd1) & (in_V_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = (((in_V_V_empty_n == 1'b0) & (ap_predicate_op170_read_state4 == 1'b1)) | ((tmp_i_2864_reg_1001 == 1'd1) & (in_V_V_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter3 = ((out_V_V_full_n == 1'b0) & (ap_predicate_op219_write_state5 == 1'b1));
end

always @ (*) begin
    ap_condition_397 = ((or_cond_i_reg_1046 == 1'd1) & (tmp_i_2864_reg_1001 == 1'd0) & (tmp_3002_fu_819_p1 == 2'd0));
end

always @ (*) begin
    ap_condition_409 = ((or_cond_i_reg_1046 == 1'd1) & (tmp_i_2864_reg_1001 == 1'd0) & (tmp_3002_fu_819_p1 == 2'd1));
end

always @ (*) begin
    ap_condition_420 = ((or_cond_i_reg_1046 == 1'd1) & (tmp_i_2864_reg_1001 == 1'd0) & (tmp_3002_fu_819_p1 == 2'd2));
end

always @ (*) begin
    ap_condition_431 = ((or_cond_i_reg_1046 == 1'd1) & (tmp_i_2864_reg_1001 == 1'd0) & (tmp_3002_fu_819_p1 == 2'd3));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op170_read_state4 = ((or_cond_i_reg_1046 == 1'd1) & (tmp_i_2864_reg_1001 == 1'd0));
end

always @ (*) begin
    ap_predicate_op219_write_state5 = ((tmp_i_2864_reg_1001_pp0_iter2_reg == 1'd0) & (tmp_111_i_reg_1005_pp0_iter2_reg == 1'd1));
end

assign bound_fu_422_p2 = (p_shl_fu_406_p1 + p_shl2_fu_418_p1);

assign count_simd_fu_554_p2 = (32'd1 + count_simd_4_fu_122);

assign counter_internal_blo_16_fu_730_p2 = (counter_internal_blo_fu_134 + 32'd1);

assign current_block_write_10_fu_846_p3 = ((tmp_124_i_reg_1050[0:0] === 1'b1) ? current_block_write_9_fu_838_p3 : current_block_write_17_fu_126);

assign current_block_write_7_fu_882_p3 = ((tmp_117_i_fu_876_p2[0:0] === 1'b1) ? 32'd0 : current_block_write_fu_870_p2);

assign current_block_write_8_fu_826_p2 = (current_block_write_17_fu_126 + 32'd1);

assign current_block_write_9_fu_838_p3 = ((tmp_125_i_fu_832_p2[0:0] === 1'b1) ? 32'd0 : current_block_write_8_fu_826_p2);

assign current_block_write_fu_870_p2 = (current_block_write_17_fu_126 + 32'd1);

assign current_line_3_i_fu_697_p3 = ((tmp_124_i_fu_376_p2[0:0] === 1'b1) ? 32'd0 : grp_fu_370_p2);

assign current_line_in_bloc_fu_540_p2 = (tmp_fu_534_p2 + k_x_4_fu_118);

assign exitcond_flatten_fu_448_p2 = ((indvar_flatten_reg_305 == bound_reg_977) ? 1'b1 : 1'b0);

assign grp_fu_370_p2 = (current_line_5_fu_130 + 32'd1);

assign i_fu_471_p3 = ((tmp_i_fu_459_p2[0:0] === 1'b1) ? 14'd1 : i_i_op_fu_465_p2);

assign i_i_op_fu_465_p2 = (i_i_reg_316 + 14'd1);

assign icmp_fu_679_p2 = ((tmp_3001_fu_669_p4 == 27'd0) ? 1'b1 : 1'b0);

assign indvar_flatten_next_fu_453_p2 = (indvar_flatten_reg_305 + 46'd1);

assign inp_fu_755_p2 = (inp_4_fu_114 + 32'd1);

assign inputBuf_0_V_address0 = tmp_113_i_fu_546_p1;

assign inputBuf_1_V_address0 = tmp_113_i_fu_546_p1;

assign inputBuf_2_V_address0 = tmp_113_i_fu_546_p1;

assign inputBuf_3_V_address0 = tmp_113_i_fu_546_p1;

assign k_x_fu_571_p2 = (k_x_4_fu_118 + 32'd1);

assign k_y_fu_528_p2 = (32'd1 + k_y_4_fu_110);

assign numReps_out_din = numReps_dout;

assign ofm_x_fu_602_p2 = (ofm_x_4_fu_106 + 32'd1);

assign ofm_y_fu_622_p2 = (ofm_y_1_i_fu_102 + 32'd1);

assign or_cond_i_fu_685_p2 = (tmp_121_i_fu_663_p2 & icmp_fu_679_p2);

assign outElem_V_fu_797_p5 = (tmp1_fu_786_p2 + tmp_2999_reg_1009);

assign out_V_V_din = outElem_V_reg_1059;

assign p_i_fu_742_p3 = ((tmp_126_i_fu_736_p2[0:0] === 1'b1) ? 32'd0 : counter_internal_blo_16_fu_730_p2);

assign p_inp_1_i_fu_634_p3 = ((tmp_120_i_fu_628_p2[0:0] === 1'b1) ? 32'd0 : inp_4_fu_114);

assign p_ofm_y_4_i_fu_642_p3 = ((tmp_120_i_fu_628_p2[0:0] === 1'b1) ? 32'd0 : ofm_y_fu_622_p2);

assign p_shl2_fu_418_p1 = tmp_17_fu_410_p3;

assign p_shl_fu_406_p1 = tmp_s_fu_398_p3;

assign read_block_1_i_mid2_fu_485_p3 = ((tmp_i_reg_991[0:0] === 1'b1) ? 32'd0 : read_block_5_fu_98);

assign read_block_3_cast_fu_691_p2 = (tmp_2997_fu_493_p1 + 6'd1);

assign read_block_3_cast_i_fu_713_p1 = read_block_3_fu_705_p3;

assign read_block_3_fu_705_p3 = ((tmp_124_i_fu_376_p2[0:0] === 1'b1) ? read_block_3_cast_fu_691_p2 : tmp_2997_fu_493_p1);

assign read_block_fu_771_p2 = (read_block_1_i_mid2_fu_485_p3 + 32'd1);

assign tmp1_fu_786_p2 = (2'd1 + tmp_3000_fu_782_p1);

assign tmp_110_i_fu_858_p1 = reg_394;

assign tmp_111_i_fu_506_p2 = ((counter_internal_blo_fu_134 < 32'd269) ? 1'b1 : 1'b0);

assign tmp_113_i_fu_546_p1 = current_line_in_bloc_fu_540_p2;

assign tmp_114_i_fu_560_p2 = ((count_simd_4_fu_122 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_115_i_fu_382_p2 = ((grp_fu_370_p2 == 32'd32) ? 1'b1 : 1'b0);

assign tmp_116_i_fu_577_p2 = ((k_x_fu_571_p2 == 32'd3) ? 1'b1 : 1'b0);

assign tmp_117_i_fu_876_p2 = ((current_block_write_fu_870_p2 == 32'd4) ? 1'b1 : 1'b0);

assign tmp_118_i_fu_588_p2 = ((k_y_fu_528_p2 == 32'd3) ? 1'b1 : 1'b0);

assign tmp_119_i_fu_608_p2 = ((ofm_x_fu_602_p2 == 32'd30) ? 1'b1 : 1'b0);

assign tmp_120_i_fu_628_p2 = ((ofm_y_fu_622_p2 == 32'd30) ? 1'b1 : 1'b0);

assign tmp_121_i_fu_663_p2 = ((counter_internal_blo_fu_134 < 32'd31) ? 1'b1 : 1'b0);

assign tmp_123_i_fu_811_p1 = reg_394;

assign tmp_124_i_fu_376_p2 = ((grp_fu_370_p2 == 32'd32) ? 1'b1 : 1'b0);

assign tmp_125_i_fu_832_p2 = ((current_block_write_8_fu_826_p2 == 32'd4) ? 1'b1 : 1'b0);

assign tmp_126_i_fu_736_p2 = ((counter_internal_blo_16_fu_730_p2 == 32'd269) ? 1'b1 : 1'b0);

assign tmp_17_fu_410_p3 = {{numReps_dout}, {2'd0}};

assign tmp_2997_fu_493_p1 = read_block_1_i_mid2_fu_485_p3[5:0];

assign tmp_2998_fu_866_p1 = current_block_write_17_fu_126[1:0];

assign tmp_2999_fu_524_p1 = k_y_4_fu_110[1:0];

assign tmp_3000_fu_782_p1 = current_block_write_17_fu_126[1:0];

assign tmp_3001_fu_669_p4 = {{read_block_1_i_mid2_fu_485_p3[31:5]}};

assign tmp_3002_fu_819_p1 = current_block_write_17_fu_126[1:0];

assign tmp_fu_534_p2 = (ofm_x_4_fu_106 + count_simd_4_fu_122);

assign tmp_i_2864_fu_497_p2 = ((inp_4_fu_114 < 32'd96) ? 1'b1 : 1'b0);

assign tmp_i_fu_459_p2 = ((i_i_reg_316 == 14'd8196) ? 1'b1 : 1'b0);

assign tmp_s_fu_398_p3 = {{numReps_dout}, {13'd0}};

always @ (posedge ap_clk) begin
    bound_reg_977[1:0] <= 2'b00;
end

endmodule //ConvolutionInputGene_2
