-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ConvolutionInputGene_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_V_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    in_V_V_empty_n : IN STD_LOGIC;
    in_V_V_read : OUT STD_LOGIC;
    out_V_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_V_V_full_n : IN STD_LOGIC;
    out_V_V_write : OUT STD_LOGIC;
    numReps_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    numReps_empty_n : IN STD_LOGIC;
    numReps_read : OUT STD_LOGIC;
    numReps_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    numReps_out_full_n : IN STD_LOGIC;
    numReps_out_write : OUT STD_LOGIC );
end;


architecture behav of ConvolutionInputGene_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv43_0 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000000000000000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv43_1 : STD_LOGIC_VECTOR (42 downto 0) := "0000000000000000000000000000000000000000001";
    constant ap_const_lv11_600 : STD_LOGIC_VECTOR (10 downto 0) := "11000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_1AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110101111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal in_V_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_i_1825_reg_999 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_reg_1029 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_V_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal tmp_i_1825_reg_999_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_148_i_reg_1003 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_148_i_reg_1003_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal numReps_blk_n : STD_LOGIC;
    signal numReps_out_blk_n : STD_LOGIC;
    signal indvar_flatten_reg_303 : STD_LOGIC_VECTOR (42 downto 0);
    signal i_i_reg_314 : STD_LOGIC_VECTOR (10 downto 0);
    signal reg_392 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_predicate_op167_read_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter3 : BOOLEAN;
    signal ap_predicate_op221_write_state6 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_i_1825_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_fu_677_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bound_fu_416_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal bound_reg_975 : STD_LOGIC_VECTOR (42 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal exitcond_flatten_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten_reg_980 : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten_next_fu_447_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal tmp_i_fu_453_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_reg_989 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_465_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_i_1825_reg_999_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_148_i_fu_500_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_148_i_reg_1003_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_304_fu_518_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_304_reg_1007 : STD_LOGIC_VECTOR (1 downto 0);
    signal current_line_in_bloc_fu_550_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_line_in_bloc_reg_1012 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_163_i_fu_374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_163_i_reg_1033 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_154_i_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_154_i_reg_1038 : STD_LOGIC_VECTOR (0 downto 0);
    signal current_block_read_fu_791_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal current_block_read_reg_1042 : STD_LOGIC_VECTOR (1 downto 0);
    signal outElem_V_fu_880_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal outElem_V_reg_1073 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal inputBuf_0_V_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal inputBuf_0_V_ce0 : STD_LOGIC;
    signal inputBuf_0_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal inputBuf_0_V_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal inputBuf_0_V_ce1 : STD_LOGIC;
    signal inputBuf_0_V_we1 : STD_LOGIC;
    signal inputBuf_1_V_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal inputBuf_1_V_ce0 : STD_LOGIC;
    signal inputBuf_1_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal inputBuf_1_V_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal inputBuf_1_V_ce1 : STD_LOGIC;
    signal inputBuf_1_V_we1 : STD_LOGIC;
    signal inputBuf_2_V_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal inputBuf_2_V_ce0 : STD_LOGIC;
    signal inputBuf_2_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal inputBuf_2_V_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal inputBuf_2_V_ce1 : STD_LOGIC;
    signal inputBuf_2_V_we1 : STD_LOGIC;
    signal inputBuf_3_V_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal inputBuf_3_V_ce0 : STD_LOGIC;
    signal inputBuf_3_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal inputBuf_3_V_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal inputBuf_3_V_ce1 : STD_LOGIC;
    signal inputBuf_3_V_we1 : STD_LOGIC;
    signal tmp_152_i_fu_778_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_162_i_fu_796_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_147_i_fu_843_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal read_block_3_fu_96 : STD_LOGIC_VECTOR (31 downto 0);
    signal read_block_1_i_mid2_fu_479_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal read_block_3_cast_i_fu_705_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal read_block_fu_763_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ofm_y_1_i_fu_100 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ofm_y_6_i_fu_644_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_153_i_fu_562_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_155_i_fu_579_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_157_i_fu_590_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_158_i_fu_610_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ofm_x_2_fu_104 : STD_LOGIC_VECTOR (31 downto 0);
    signal ofm_x_fu_604_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_y_2_fu_108 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_y_fu_522_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal inp_2_fu_112 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_inp_1_i_fu_636_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal inp_fu_747_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_x_2_fu_116 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_x_fu_573_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_simd_2_fu_120 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_simd_fu_556_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_block_write_9_fu_124 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_block_write_8_1822_fu_831_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_block_write_5_1819_fu_867_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_line_3_fu_128 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_line_3_i_fu_689_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_368_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal counter_internal_blo_fu_132 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_i_fu_734_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_308_fu_804_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_303_fu_851_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_404_p3 : STD_LOGIC_VECTOR (40 downto 0);
    signal p_shl_fu_396_p3 : STD_LOGIC_VECTOR (42 downto 0);
    signal p_shl2_fu_412_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal i_i_op_fu_459_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_307_fu_532_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_306_fu_528_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_149_i_fu_536_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_151_i_fu_542_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ofm_y_fu_624_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_159_i_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_160_i_fu_665_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_161_i_fu_671_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_302_fu_487_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal read_block_5_cast_fu_683_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal read_block_2_fu_697_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal counter_internal_blo_8_fu_722_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_165_i_fu_728_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_305_fu_774_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_785_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal current_block_write_6_1820_fu_811_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_164_i_fu_817_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal current_block_write_7_1821_fu_823_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_block_write_fu_855_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_156_i_fu_861_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_condition_410 : BOOLEAN;
    signal ap_condition_422 : BOOLEAN;
    signal ap_condition_433 : BOOLEAN;
    signal ap_condition_444 : BOOLEAN;

    component BBJ_u96_cnvW2A2_mdSL IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component ConvolutionInputGdOK IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address1 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    inputBuf_0_V_U : component ConvolutionInputGdOK
    generic map (
        DataWidth => 16,
        AddressRange => 80,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_0_V_address0,
        ce0 => inputBuf_0_V_ce0,
        q0 => inputBuf_0_V_q0,
        address1 => inputBuf_0_V_address1,
        ce1 => inputBuf_0_V_ce1,
        we1 => inputBuf_0_V_we1,
        d1 => in_V_V_dout);

    inputBuf_1_V_U : component ConvolutionInputGdOK
    generic map (
        DataWidth => 16,
        AddressRange => 80,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_1_V_address0,
        ce0 => inputBuf_1_V_ce0,
        q0 => inputBuf_1_V_q0,
        address1 => inputBuf_1_V_address1,
        ce1 => inputBuf_1_V_ce1,
        we1 => inputBuf_1_V_we1,
        d1 => in_V_V_dout);

    inputBuf_2_V_U : component ConvolutionInputGdOK
    generic map (
        DataWidth => 16,
        AddressRange => 80,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_2_V_address0,
        ce0 => inputBuf_2_V_ce0,
        q0 => inputBuf_2_V_q0,
        address1 => inputBuf_2_V_address1,
        ce1 => inputBuf_2_V_ce1,
        we1 => inputBuf_2_V_we1,
        d1 => in_V_V_dout);

    inputBuf_3_V_U : component ConvolutionInputGdOK
    generic map (
        DataWidth => 16,
        AddressRange => 80,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_3_V_address0,
        ce0 => inputBuf_3_V_ce0,
        q0 => inputBuf_3_V_q0,
        address1 => inputBuf_3_V_address1,
        ce1 => inputBuf_3_V_ce1,
        we1 => inputBuf_3_V_we1,
        d1 => in_V_V_dout);

    BBJ_u96_cnvW2A2_mdSL_U832 : component BBJ_u96_cnvW2A2_mdSL
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => inputBuf_0_V_q0,
        din1 => inputBuf_1_V_q0,
        din2 => inputBuf_2_V_q0,
        din3 => inputBuf_3_V_q0,
        din4 => current_block_read_reg_1042,
        dout => outElem_V_fu_880_p6);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                elsif ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    count_simd_2_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_153_i_fu_562_p2 = ap_const_lv1_0) and (tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (tmp_148_i_fu_500_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                count_simd_2_fu_120 <= count_simd_fu_556_p2;
            elsif ((((tmp_155_i_fu_579_p2 = ap_const_lv1_0) and (tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (tmp_153_i_fu_562_p2 = ap_const_lv1_1) and (tmp_148_i_fu_500_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_157_i_fu_590_p2 = ap_const_lv1_0) and (tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (tmp_155_i_fu_579_p2 = ap_const_lv1_1) and (tmp_153_i_fu_562_p2 = ap_const_lv1_1) and (tmp_148_i_fu_500_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_158_i_fu_610_p2 = ap_const_lv1_0) and (tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (tmp_157_i_fu_590_p2 = ap_const_lv1_1) and (tmp_155_i_fu_579_p2 = ap_const_lv1_1) and (tmp_153_i_fu_562_p2 = ap_const_lv1_1) and (tmp_148_i_fu_500_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (tmp_158_i_fu_610_p2 = ap_const_lv1_1) and (tmp_157_i_fu_590_p2 = ap_const_lv1_1) and (tmp_155_i_fu_579_p2 = ap_const_lv1_1) and (tmp_153_i_fu_562_p2 = ap_const_lv1_1) and (tmp_148_i_fu_500_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                count_simd_2_fu_120 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    counter_internal_blo_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                counter_internal_blo_fu_132 <= p_i_fu_734_p3;
            elsif ((((tmp_154_i_fu_380_p2 = ap_const_lv1_1) and (tmp_i_1825_fu_491_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                counter_internal_blo_fu_132 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    current_block_write_9_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_154_i_reg_1038 = ap_const_lv1_1) and (tmp_i_1825_reg_999 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                current_block_write_9_fu_124 <= current_block_write_5_1819_fu_867_p3;
            elsif (((or_cond_i_reg_1029 = ap_const_lv1_1) and (tmp_i_1825_reg_999 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                current_block_write_9_fu_124 <= current_block_write_8_1822_fu_831_p3;
            elsif ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                current_block_write_9_fu_124 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    current_line_3_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_154_i_fu_380_p2 = ap_const_lv1_0) and (tmp_i_1825_fu_491_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                current_line_3_fu_128 <= grp_fu_368_p2;
            elsif (((tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (or_cond_i_fu_677_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                current_line_3_fu_128 <= current_line_3_i_fu_689_p3;
            elsif ((((tmp_154_i_fu_380_p2 = ap_const_lv1_1) and (tmp_i_1825_fu_491_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                current_line_3_fu_128 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    i_i_reg_314_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_fu_442_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                i_i_reg_314 <= i_fu_465_p3;
            elsif ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_i_reg_314 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_303_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_fu_442_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten_reg_303 <= indvar_flatten_next_fu_447_p2;
            elsif ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten_reg_303 <= ap_const_lv43_0;
            end if; 
        end if;
    end process;

    inp_2_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_1825_fu_491_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                inp_2_fu_112 <= inp_fu_747_p2;
            elsif (((tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (tmp_158_i_fu_610_p2 = ap_const_lv1_1) and (tmp_157_i_fu_590_p2 = ap_const_lv1_1) and (tmp_155_i_fu_579_p2 = ap_const_lv1_1) and (tmp_153_i_fu_562_p2 = ap_const_lv1_1) and (tmp_148_i_fu_500_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                inp_2_fu_112 <= p_inp_1_i_fu_636_p3;
            elsif ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                inp_2_fu_112 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    k_x_2_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_155_i_fu_579_p2 = ap_const_lv1_0) and (tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (tmp_153_i_fu_562_p2 = ap_const_lv1_1) and (tmp_148_i_fu_500_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                k_x_2_fu_116 <= k_x_fu_573_p2;
            elsif ((((tmp_157_i_fu_590_p2 = ap_const_lv1_0) and (tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (tmp_155_i_fu_579_p2 = ap_const_lv1_1) and (tmp_153_i_fu_562_p2 = ap_const_lv1_1) and (tmp_148_i_fu_500_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_158_i_fu_610_p2 = ap_const_lv1_0) and (tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (tmp_157_i_fu_590_p2 = ap_const_lv1_1) and (tmp_155_i_fu_579_p2 = ap_const_lv1_1) and (tmp_153_i_fu_562_p2 = ap_const_lv1_1) and (tmp_148_i_fu_500_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (tmp_158_i_fu_610_p2 = ap_const_lv1_1) and (tmp_157_i_fu_590_p2 = ap_const_lv1_1) and (tmp_155_i_fu_579_p2 = ap_const_lv1_1) and (tmp_153_i_fu_562_p2 = ap_const_lv1_1) and (tmp_148_i_fu_500_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                k_x_2_fu_116 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    k_y_2_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_157_i_fu_590_p2 = ap_const_lv1_0) and (tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (tmp_155_i_fu_579_p2 = ap_const_lv1_1) and (tmp_153_i_fu_562_p2 = ap_const_lv1_1) and (tmp_148_i_fu_500_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                k_y_2_fu_108 <= k_y_fu_522_p2;
            elsif ((((tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (tmp_157_i_fu_590_p2 = ap_const_lv1_1) and (tmp_155_i_fu_579_p2 = ap_const_lv1_1) and (tmp_153_i_fu_562_p2 = ap_const_lv1_1) and (tmp_148_i_fu_500_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                k_y_2_fu_108 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    ofm_x_2_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_158_i_fu_610_p2 = ap_const_lv1_0) and (tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (tmp_157_i_fu_590_p2 = ap_const_lv1_1) and (tmp_155_i_fu_579_p2 = ap_const_lv1_1) and (tmp_153_i_fu_562_p2 = ap_const_lv1_1) and (tmp_148_i_fu_500_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                ofm_x_2_fu_104 <= ofm_x_fu_604_p2;
            elsif ((((tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (tmp_158_i_fu_610_p2 = ap_const_lv1_1) and (tmp_157_i_fu_590_p2 = ap_const_lv1_1) and (tmp_155_i_fu_579_p2 = ap_const_lv1_1) and (tmp_153_i_fu_562_p2 = ap_const_lv1_1) and (tmp_148_i_fu_500_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                ofm_x_2_fu_104 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    ofm_y_1_i_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (tmp_158_i_fu_610_p2 = ap_const_lv1_1) and (tmp_157_i_fu_590_p2 = ap_const_lv1_1) and (tmp_155_i_fu_579_p2 = ap_const_lv1_1) and (tmp_153_i_fu_562_p2 = ap_const_lv1_1) and (tmp_148_i_fu_500_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                ofm_y_1_i_fu_100 <= p_ofm_y_6_i_fu_644_p3;
            elsif ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                ofm_y_1_i_fu_100 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    read_block_3_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_154_i_fu_380_p2 = ap_const_lv1_1) and (tmp_i_1825_fu_491_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                read_block_3_fu_96 <= read_block_fu_763_p2;
            elsif (((tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (or_cond_i_fu_677_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                read_block_3_fu_96 <= read_block_3_cast_i_fu_705_p1;
            elsif ((((tmp_154_i_fu_380_p2 = ap_const_lv1_0) and (tmp_i_1825_fu_491_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((or_cond_i_fu_677_p2 = ap_const_lv1_0) and (tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                read_block_3_fu_96 <= read_block_1_i_mid2_fu_479_p3;
            elsif ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                read_block_3_fu_96 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    bound_reg_975(42 downto 9) <= bound_fu_416_p2(42 downto 9);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_148_i_reg_1003 = ap_const_lv1_1) and (tmp_i_1825_reg_999 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                current_block_read_reg_1042 <= current_block_read_fu_791_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (tmp_148_i_fu_500_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                current_line_in_bloc_reg_1012 <= current_line_in_bloc_fu_550_p2;
                tmp_304_reg_1007 <= tmp_304_fu_518_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                exitcond_flatten_reg_980 <= exitcond_flatten_fu_442_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                or_cond_i_reg_1029 <= or_cond_i_fu_677_p2;
                tmp_148_i_reg_1003 <= tmp_148_i_fu_500_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_1825_reg_999_pp0_iter2_reg = ap_const_lv1_0) and (tmp_148_i_reg_1003_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                outElem_V_reg_1073 <= outElem_V_fu_880_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((tmp_i_1825_fu_491_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (or_cond_i_fu_677_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then
                reg_392 <= current_line_3_fu_128;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                tmp_148_i_reg_1003_pp0_iter2_reg <= tmp_148_i_reg_1003;
                tmp_148_i_reg_1003_pp0_iter3_reg <= tmp_148_i_reg_1003_pp0_iter2_reg;
                tmp_i_1825_reg_999_pp0_iter2_reg <= tmp_i_1825_reg_999;
                tmp_i_1825_reg_999_pp0_iter3_reg <= tmp_i_1825_reg_999_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_1825_fu_491_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_154_i_reg_1038 <= tmp_154_i_fu_380_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_1825_fu_491_p2 = ap_const_lv1_0) and (or_cond_i_fu_677_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_163_i_reg_1033 <= tmp_163_i_fu_374_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_reg_980 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_i_1825_reg_999 <= tmp_i_1825_fu_491_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_fu_442_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_i_reg_989 <= tmp_i_fu_453_p2;
            end if;
        end if;
    end process;
    bound_reg_975(8 downto 0) <= "000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, numReps_empty_n, numReps_out_full_n, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter1, exitcond_flatten_fu_442_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (exitcond_flatten_fu_442_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) and not(((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (exitcond_flatten_fu_442_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state7 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(in_V_V_empty_n, out_V_V_full_n, ap_enable_reg_pp0_iter2, tmp_i_1825_reg_999, ap_enable_reg_pp0_iter4, ap_predicate_op167_read_state4, ap_predicate_op221_write_state6)
    begin
                ap_block_pp0_stage0_01001 <= (((out_V_V_full_n = ap_const_logic_0) and (ap_predicate_op221_write_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((in_V_V_empty_n = ap_const_logic_0) and (ap_predicate_op167_read_state4 = ap_const_boolean_1)) or ((tmp_i_1825_reg_999 = ap_const_lv1_1) and (in_V_V_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(in_V_V_empty_n, out_V_V_full_n, ap_enable_reg_pp0_iter2, tmp_i_1825_reg_999, ap_enable_reg_pp0_iter4, ap_predicate_op167_read_state4, ap_predicate_op221_write_state6)
    begin
                ap_block_pp0_stage0_11001 <= (((out_V_V_full_n = ap_const_logic_0) and (ap_predicate_op221_write_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((in_V_V_empty_n = ap_const_logic_0) and (ap_predicate_op167_read_state4 = ap_const_boolean_1)) or ((tmp_i_1825_reg_999 = ap_const_lv1_1) and (in_V_V_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(in_V_V_empty_n, out_V_V_full_n, ap_enable_reg_pp0_iter2, tmp_i_1825_reg_999, ap_enable_reg_pp0_iter4, ap_predicate_op167_read_state4, ap_predicate_op221_write_state6)
    begin
                ap_block_pp0_stage0_subdone <= (((out_V_V_full_n = ap_const_logic_0) and (ap_predicate_op221_write_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((in_V_V_empty_n = ap_const_logic_0) and (ap_predicate_op167_read_state4 = ap_const_boolean_1)) or ((tmp_i_1825_reg_999 = ap_const_lv1_1) and (in_V_V_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, numReps_empty_n, numReps_out_full_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_pp0_stage0_iter2_assign_proc : process(in_V_V_empty_n, tmp_i_1825_reg_999, ap_predicate_op167_read_state4)
    begin
                ap_block_state4_pp0_stage0_iter2 <= (((in_V_V_empty_n = ap_const_logic_0) and (ap_predicate_op167_read_state4 = ap_const_boolean_1)) or ((tmp_i_1825_reg_999 = ap_const_lv1_1) and (in_V_V_empty_n = ap_const_logic_0)));
    end process;

        ap_block_state5_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state6_pp0_stage0_iter4_assign_proc : process(out_V_V_full_n, ap_predicate_op221_write_state6)
    begin
                ap_block_state6_pp0_stage0_iter4 <= ((out_V_V_full_n = ap_const_logic_0) and (ap_predicate_op221_write_state6 = ap_const_boolean_1));
    end process;


    ap_condition_410_assign_proc : process(tmp_i_1825_reg_999, or_cond_i_reg_1029, tmp_308_fu_804_p1)
    begin
                ap_condition_410 <= ((or_cond_i_reg_1029 = ap_const_lv1_1) and (tmp_i_1825_reg_999 = ap_const_lv1_0) and (tmp_308_fu_804_p1 = ap_const_lv2_0));
    end process;


    ap_condition_422_assign_proc : process(tmp_i_1825_reg_999, or_cond_i_reg_1029, tmp_308_fu_804_p1)
    begin
                ap_condition_422 <= ((or_cond_i_reg_1029 = ap_const_lv1_1) and (tmp_i_1825_reg_999 = ap_const_lv1_0) and (tmp_308_fu_804_p1 = ap_const_lv2_1));
    end process;


    ap_condition_433_assign_proc : process(tmp_i_1825_reg_999, or_cond_i_reg_1029, tmp_308_fu_804_p1)
    begin
                ap_condition_433 <= ((or_cond_i_reg_1029 = ap_const_lv1_1) and (tmp_i_1825_reg_999 = ap_const_lv1_0) and (tmp_308_fu_804_p1 = ap_const_lv2_2));
    end process;


    ap_condition_444_assign_proc : process(tmp_i_1825_reg_999, or_cond_i_reg_1029, tmp_308_fu_804_p1)
    begin
                ap_condition_444 <= ((or_cond_i_reg_1029 = ap_const_lv1_1) and (tmp_i_1825_reg_999 = ap_const_lv1_0) and (tmp_308_fu_804_p1 = ap_const_lv2_3));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(exitcond_flatten_fu_442_p2)
    begin
        if ((exitcond_flatten_fu_442_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op167_read_state4_assign_proc : process(tmp_i_1825_reg_999, or_cond_i_reg_1029)
    begin
                ap_predicate_op167_read_state4 <= ((or_cond_i_reg_1029 = ap_const_lv1_1) and (tmp_i_1825_reg_999 = ap_const_lv1_0));
    end process;


    ap_predicate_op221_write_state6_assign_proc : process(tmp_i_1825_reg_999_pp0_iter3_reg, tmp_148_i_reg_1003_pp0_iter3_reg)
    begin
                ap_predicate_op221_write_state6 <= ((tmp_i_1825_reg_999_pp0_iter3_reg = ap_const_lv1_0) and (tmp_148_i_reg_1003_pp0_iter3_reg = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bound_fu_416_p2 <= std_logic_vector(unsigned(p_shl_fu_396_p3) - unsigned(p_shl2_fu_412_p1));
    count_simd_fu_556_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(count_simd_2_fu_120));
    counter_internal_blo_8_fu_722_p2 <= std_logic_vector(unsigned(counter_internal_blo_fu_132) + unsigned(ap_const_lv32_1));
    current_block_read_fu_791_p2 <= std_logic_vector(unsigned(tmp_fu_785_p2) + unsigned(tmp_304_reg_1007));
    current_block_write_5_1819_fu_867_p3 <= 
        ap_const_lv32_0 when (tmp_156_i_fu_861_p2(0) = '1') else 
        current_block_write_fu_855_p2;
    current_block_write_6_1820_fu_811_p2 <= std_logic_vector(unsigned(current_block_write_9_fu_124) + unsigned(ap_const_lv32_1));
    current_block_write_7_1821_fu_823_p3 <= 
        ap_const_lv32_0 when (tmp_164_i_fu_817_p2(0) = '1') else 
        current_block_write_6_1820_fu_811_p2;
    current_block_write_8_1822_fu_831_p3 <= 
        current_block_write_7_1821_fu_823_p3 when (tmp_163_i_reg_1033(0) = '1') else 
        current_block_write_9_fu_124;
    current_block_write_fu_855_p2 <= std_logic_vector(unsigned(current_block_write_9_fu_124) + unsigned(ap_const_lv32_1));
    current_line_3_i_fu_689_p3 <= 
        ap_const_lv32_0 when (tmp_163_i_fu_374_p2(0) = '1') else 
        grp_fu_368_p2;
    current_line_in_bloc_fu_550_p2 <= std_logic_vector(unsigned(tmp_151_i_fu_542_p3) + unsigned(count_simd_2_fu_120));
    exitcond_flatten_fu_442_p2 <= "1" when (indvar_flatten_reg_303 = bound_reg_975) else "0";
    grp_fu_368_p2 <= std_logic_vector(unsigned(current_line_3_fu_128) + unsigned(ap_const_lv32_1));
    i_fu_465_p3 <= 
        ap_const_lv11_1 when (tmp_i_fu_453_p2(0) = '1') else 
        i_i_op_fu_459_p2;
    i_i_op_fu_459_p2 <= std_logic_vector(unsigned(i_i_reg_314) + unsigned(ap_const_lv11_1));

    in_V_V_blk_n_assign_proc : process(in_V_V_empty_n, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, tmp_i_1825_reg_999, or_cond_i_reg_1029)
    begin
        if ((((or_cond_i_reg_1029 = ap_const_lv1_1) and (tmp_i_1825_reg_999 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((tmp_i_1825_reg_999 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
            in_V_V_blk_n <= in_V_V_empty_n;
        else 
            in_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_V_V_read_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_1825_reg_999, ap_predicate_op167_read_state4, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_predicate_op167_read_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_1825_reg_999 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            in_V_V_read <= ap_const_logic_1;
        else 
            in_V_V_read <= ap_const_logic_0;
        end if; 
    end process;

    indvar_flatten_next_fu_447_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_303) + unsigned(ap_const_lv43_1));
    inp_fu_747_p2 <= std_logic_vector(unsigned(inp_2_fu_112) + unsigned(ap_const_lv32_1));
    inputBuf_0_V_address0 <= tmp_152_i_fu_778_p1(7 - 1 downto 0);

    inputBuf_0_V_address1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, tmp_i_1825_reg_999, tmp_162_i_fu_796_p1, tmp_147_i_fu_843_p1, tmp_303_fu_851_p1, ap_condition_410)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if (((tmp_i_1825_reg_999 = ap_const_lv1_1) and (tmp_303_fu_851_p1 = ap_const_lv2_0))) then 
                inputBuf_0_V_address1 <= tmp_147_i_fu_843_p1(7 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_410)) then 
                inputBuf_0_V_address1 <= tmp_162_i_fu_796_p1(7 - 1 downto 0);
            else 
                inputBuf_0_V_address1 <= "XXXXXXX";
            end if;
        else 
            inputBuf_0_V_address1 <= "XXXXXXX";
        end if; 
    end process;


    inputBuf_0_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            inputBuf_0_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_0_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_1825_reg_999, or_cond_i_reg_1029, ap_block_pp0_stage0_11001, tmp_308_fu_804_p1, tmp_303_fu_851_p1)
    begin
        if ((((or_cond_i_reg_1029 = ap_const_lv1_1) and (tmp_i_1825_reg_999 = ap_const_lv1_0) and (tmp_308_fu_804_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_1825_reg_999 = ap_const_lv1_1) and (tmp_303_fu_851_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_0_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_0_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_0_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_1825_reg_999, or_cond_i_reg_1029, ap_block_pp0_stage0_11001, tmp_308_fu_804_p1, tmp_303_fu_851_p1)
    begin
        if ((((or_cond_i_reg_1029 = ap_const_lv1_1) and (tmp_i_1825_reg_999 = ap_const_lv1_0) and (tmp_308_fu_804_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_1825_reg_999 = ap_const_lv1_1) and (tmp_303_fu_851_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_0_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_0_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    inputBuf_1_V_address0 <= tmp_152_i_fu_778_p1(7 - 1 downto 0);

    inputBuf_1_V_address1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, tmp_i_1825_reg_999, tmp_162_i_fu_796_p1, tmp_147_i_fu_843_p1, tmp_303_fu_851_p1, ap_condition_422)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if (((tmp_i_1825_reg_999 = ap_const_lv1_1) and (tmp_303_fu_851_p1 = ap_const_lv2_1))) then 
                inputBuf_1_V_address1 <= tmp_147_i_fu_843_p1(7 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_422)) then 
                inputBuf_1_V_address1 <= tmp_162_i_fu_796_p1(7 - 1 downto 0);
            else 
                inputBuf_1_V_address1 <= "XXXXXXX";
            end if;
        else 
            inputBuf_1_V_address1 <= "XXXXXXX";
        end if; 
    end process;


    inputBuf_1_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            inputBuf_1_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_1_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_1825_reg_999, or_cond_i_reg_1029, ap_block_pp0_stage0_11001, tmp_308_fu_804_p1, tmp_303_fu_851_p1)
    begin
        if ((((or_cond_i_reg_1029 = ap_const_lv1_1) and (tmp_i_1825_reg_999 = ap_const_lv1_0) and (tmp_308_fu_804_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_1825_reg_999 = ap_const_lv1_1) and (tmp_303_fu_851_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_1_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_1_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_1_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_1825_reg_999, or_cond_i_reg_1029, ap_block_pp0_stage0_11001, tmp_308_fu_804_p1, tmp_303_fu_851_p1)
    begin
        if ((((or_cond_i_reg_1029 = ap_const_lv1_1) and (tmp_i_1825_reg_999 = ap_const_lv1_0) and (tmp_308_fu_804_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_1825_reg_999 = ap_const_lv1_1) and (tmp_303_fu_851_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_1_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_1_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    inputBuf_2_V_address0 <= tmp_152_i_fu_778_p1(7 - 1 downto 0);

    inputBuf_2_V_address1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, tmp_i_1825_reg_999, tmp_162_i_fu_796_p1, tmp_147_i_fu_843_p1, tmp_303_fu_851_p1, ap_condition_433)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if (((tmp_i_1825_reg_999 = ap_const_lv1_1) and (tmp_303_fu_851_p1 = ap_const_lv2_2))) then 
                inputBuf_2_V_address1 <= tmp_147_i_fu_843_p1(7 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_433)) then 
                inputBuf_2_V_address1 <= tmp_162_i_fu_796_p1(7 - 1 downto 0);
            else 
                inputBuf_2_V_address1 <= "XXXXXXX";
            end if;
        else 
            inputBuf_2_V_address1 <= "XXXXXXX";
        end if; 
    end process;


    inputBuf_2_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            inputBuf_2_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_2_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_1825_reg_999, or_cond_i_reg_1029, ap_block_pp0_stage0_11001, tmp_308_fu_804_p1, tmp_303_fu_851_p1)
    begin
        if ((((or_cond_i_reg_1029 = ap_const_lv1_1) and (tmp_i_1825_reg_999 = ap_const_lv1_0) and (tmp_308_fu_804_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_1825_reg_999 = ap_const_lv1_1) and (tmp_303_fu_851_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_2_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_2_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_2_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_1825_reg_999, or_cond_i_reg_1029, ap_block_pp0_stage0_11001, tmp_308_fu_804_p1, tmp_303_fu_851_p1)
    begin
        if ((((or_cond_i_reg_1029 = ap_const_lv1_1) and (tmp_i_1825_reg_999 = ap_const_lv1_0) and (tmp_308_fu_804_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_1825_reg_999 = ap_const_lv1_1) and (tmp_303_fu_851_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_2_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_2_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    inputBuf_3_V_address0 <= tmp_152_i_fu_778_p1(7 - 1 downto 0);

    inputBuf_3_V_address1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, tmp_i_1825_reg_999, tmp_162_i_fu_796_p1, tmp_147_i_fu_843_p1, tmp_303_fu_851_p1, ap_condition_444)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if (((tmp_i_1825_reg_999 = ap_const_lv1_1) and (tmp_303_fu_851_p1 = ap_const_lv2_3))) then 
                inputBuf_3_V_address1 <= tmp_147_i_fu_843_p1(7 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_444)) then 
                inputBuf_3_V_address1 <= tmp_162_i_fu_796_p1(7 - 1 downto 0);
            else 
                inputBuf_3_V_address1 <= "XXXXXXX";
            end if;
        else 
            inputBuf_3_V_address1 <= "XXXXXXX";
        end if; 
    end process;


    inputBuf_3_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            inputBuf_3_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_3_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_3_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_1825_reg_999, or_cond_i_reg_1029, ap_block_pp0_stage0_11001, tmp_308_fu_804_p1, tmp_303_fu_851_p1)
    begin
        if ((((or_cond_i_reg_1029 = ap_const_lv1_1) and (tmp_i_1825_reg_999 = ap_const_lv1_0) and (tmp_308_fu_804_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_1825_reg_999 = ap_const_lv1_1) and (tmp_303_fu_851_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_3_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_3_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_3_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_1825_reg_999, or_cond_i_reg_1029, ap_block_pp0_stage0_11001, tmp_308_fu_804_p1, tmp_303_fu_851_p1)
    begin
        if ((((or_cond_i_reg_1029 = ap_const_lv1_1) and (tmp_i_1825_reg_999 = ap_const_lv1_0) and (tmp_308_fu_804_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_1825_reg_999 = ap_const_lv1_1) and (tmp_303_fu_851_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_3_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_3_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_x_fu_573_p2 <= std_logic_vector(unsigned(k_x_2_fu_116) + unsigned(ap_const_lv32_1));
    k_y_fu_522_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(k_y_2_fu_108));

    numReps_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, numReps_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numReps_blk_n <= numReps_empty_n;
        else 
            numReps_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    numReps_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, numReps_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numReps_out_blk_n <= numReps_out_full_n;
        else 
            numReps_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    numReps_out_din <= numReps_dout;

    numReps_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, numReps_empty_n, numReps_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numReps_out_write <= ap_const_logic_1;
        else 
            numReps_out_write <= ap_const_logic_0;
        end if; 
    end process;


    numReps_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, numReps_empty_n, numReps_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numReps_read <= ap_const_logic_1;
        else 
            numReps_read <= ap_const_logic_0;
        end if; 
    end process;

    ofm_x_fu_604_p2 <= std_logic_vector(unsigned(ofm_x_2_fu_104) + unsigned(ap_const_lv32_1));
    ofm_y_fu_624_p2 <= std_logic_vector(unsigned(ofm_y_1_i_fu_100) + unsigned(ap_const_lv32_1));
    or_cond_i_fu_677_p2 <= (tmp_161_i_fu_671_p2 and tmp_160_i_fu_665_p2);

    out_V_V_blk_n_assign_proc : process(out_V_V_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter4, tmp_i_1825_reg_999_pp0_iter3_reg, tmp_148_i_reg_1003_pp0_iter3_reg)
    begin
        if (((tmp_i_1825_reg_999_pp0_iter3_reg = ap_const_lv1_0) and (tmp_148_i_reg_1003_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            out_V_V_blk_n <= out_V_V_full_n;
        else 
            out_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_V_V_din <= outElem_V_reg_1073;

    out_V_V_write_assign_proc : process(ap_enable_reg_pp0_iter4, ap_predicate_op221_write_state6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op221_write_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            out_V_V_write <= ap_const_logic_1;
        else 
            out_V_V_write <= ap_const_logic_0;
        end if; 
    end process;

    p_i_fu_734_p3 <= 
        ap_const_lv32_0 when (tmp_165_i_fu_728_p2(0) = '1') else 
        counter_internal_blo_8_fu_722_p2;
    p_inp_1_i_fu_636_p3 <= 
        ap_const_lv32_0 when (tmp_159_i_fu_630_p2(0) = '1') else 
        inp_2_fu_112;
    p_ofm_y_6_i_fu_644_p3 <= 
        ap_const_lv32_0 when (tmp_159_i_fu_630_p2(0) = '1') else 
        ofm_y_fu_624_p2;
    p_shl2_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_404_p3),43));
    p_shl_fu_396_p3 <= (numReps_dout & ap_const_lv11_0);
    read_block_1_i_mid2_fu_479_p3 <= 
        ap_const_lv32_0 when (tmp_i_reg_989(0) = '1') else 
        read_block_3_fu_96;
    read_block_2_fu_697_p3 <= 
        read_block_5_cast_fu_683_p2 when (tmp_163_i_fu_374_p2(0) = '1') else 
        tmp_302_fu_487_p1;
    read_block_3_cast_i_fu_705_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(read_block_2_fu_697_p3),32));
    read_block_5_cast_fu_683_p2 <= std_logic_vector(unsigned(tmp_302_fu_487_p1) + unsigned(ap_const_lv3_1));
    read_block_fu_763_p2 <= std_logic_vector(unsigned(read_block_1_i_mid2_fu_479_p3) + unsigned(ap_const_lv32_1));
    tmp_147_i_fu_843_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_392),64));
    tmp_148_i_fu_500_p2 <= "1" when (unsigned(counter_internal_blo_fu_132) < unsigned(ap_const_lv32_1AF)) else "0";
    tmp_149_i_fu_536_p2 <= std_logic_vector(unsigned(tmp_307_fu_532_p1) + unsigned(tmp_306_fu_528_p1));
    tmp_151_i_fu_542_p3 <= (tmp_149_i_fu_536_p2 & ap_const_lv4_0);
    tmp_152_i_fu_778_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(current_line_in_bloc_reg_1012),64));
    tmp_153_i_fu_562_p2 <= "1" when (count_simd_fu_556_p2 = ap_const_lv32_10) else "0";
    tmp_154_i_fu_380_p2 <= "1" when (grp_fu_368_p2 = ap_const_lv32_50) else "0";
    tmp_155_i_fu_579_p2 <= "1" when (k_x_fu_573_p2 = ap_const_lv32_3) else "0";
    tmp_156_i_fu_861_p2 <= "1" when (current_block_write_fu_855_p2 = ap_const_lv32_4) else "0";
    tmp_157_i_fu_590_p2 <= "1" when (k_y_fu_522_p2 = ap_const_lv32_3) else "0";
    tmp_158_i_fu_610_p2 <= "1" when (ofm_x_fu_604_p2 = ap_const_lv32_3) else "0";
    tmp_159_i_fu_630_p2 <= "1" when (ofm_y_fu_624_p2 = ap_const_lv32_3) else "0";
    tmp_160_i_fu_665_p2 <= "1" when (unsigned(counter_internal_blo_fu_132) < unsigned(ap_const_lv32_4F)) else "0";
    tmp_161_i_fu_671_p2 <= "1" when (unsigned(read_block_1_i_mid2_fu_479_p3) < unsigned(ap_const_lv32_5)) else "0";
    tmp_162_i_fu_796_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_392),64));
    tmp_163_i_fu_374_p2 <= "1" when (grp_fu_368_p2 = ap_const_lv32_50) else "0";
    tmp_164_i_fu_817_p2 <= "1" when (current_block_write_6_1820_fu_811_p2 = ap_const_lv32_4) else "0";
    tmp_165_i_fu_728_p2 <= "1" when (counter_internal_blo_8_fu_722_p2 = ap_const_lv32_1AF) else "0";
    tmp_302_fu_487_p1 <= read_block_1_i_mid2_fu_479_p3(3 - 1 downto 0);
    tmp_303_fu_851_p1 <= current_block_write_9_fu_124(2 - 1 downto 0);
    tmp_304_fu_518_p1 <= k_y_2_fu_108(2 - 1 downto 0);
    tmp_305_fu_774_p1 <= current_block_write_9_fu_124(2 - 1 downto 0);
    tmp_306_fu_528_p1 <= k_x_2_fu_116(28 - 1 downto 0);
    tmp_307_fu_532_p1 <= ofm_x_2_fu_104(28 - 1 downto 0);
    tmp_308_fu_804_p1 <= current_block_write_9_fu_124(2 - 1 downto 0);
    tmp_fu_785_p2 <= std_logic_vector(unsigned(ap_const_lv2_1) + unsigned(tmp_305_fu_774_p1));
    tmp_i_1825_fu_491_p2 <= "1" when (unsigned(inp_2_fu_112) < unsigned(ap_const_lv32_F0)) else "0";
    tmp_i_fu_453_p2 <= "1" when (i_i_reg_314 = ap_const_lv11_600) else "0";
    tmp_s_fu_404_p3 <= (numReps_dout & ap_const_lv9_0);
end behav;
