-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ConvolutionInputGene is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    in_V_V_empty_n : IN STD_LOGIC;
    in_V_V_read : OUT STD_LOGIC;
    out_V_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_V_V_full_n : IN STD_LOGIC;
    out_V_V_write : OUT STD_LOGIC;
    numReps_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    numReps_empty_n : IN STD_LOGIC;
    numReps_read : OUT STD_LOGIC;
    numReps_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    numReps_out_full_n : IN STD_LOGIC;
    numReps_out_write : OUT STD_LOGIC );
end;


architecture behav of ConvolutionInputGene is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv46_0 : STD_LOGIC_VECTOR (45 downto 0) := "0000000000000000000000000000000000000000000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv46_37D4 : STD_LOGIC_VECTOR (45 downto 0) := "0000000000000000000000000000000011011111010100";
    constant ap_const_lv46_1 : STD_LOGIC_VECTOR (45 downto 0) := "0000000000000000000000000000000000000000000001";
    constant ap_const_lv14_37D4 : STD_LOGIC_VECTOR (13 downto 0) := "11011111010100";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv32_B4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110100";
    constant ap_const_lv32_1F7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111110111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal in_V_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_i_2871_reg_990 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_reg_1020 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_V_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal tmp_i_2871_reg_990_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_73_i_reg_994 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_73_i_reg_994_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal numReps_blk_n : STD_LOGIC;
    signal numReps_out_blk_n : STD_LOGIC;
    signal indvar_flatten_reg_301 : STD_LOGIC_VECTOR (45 downto 0);
    signal i_i_reg_312 : STD_LOGIC_VECTOR (13 downto 0);
    signal reg_390 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_state7_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter1 : BOOLEAN;
    signal ap_predicate_op174_read_state9 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter3 : BOOLEAN;
    signal ap_predicate_op228_write_state11 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_i_2871_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_fu_658_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal numReps_read_reg_956 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_fu_417_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal bound_reg_966 : STD_LOGIC_VECTOR (45 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal exitcond_flatten_fu_423_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten_reg_971 : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten_next_fu_428_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal tmp_i_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_reg_980 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_446_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_i_2871_reg_990_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_73_i_fu_481_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_73_i_reg_994_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3012_fu_499_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3012_reg_998 : STD_LOGIC_VECTOR (1 downto 0);
    signal current_line_in_bloc_fu_531_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_line_in_bloc_reg_1003 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_88_i_fu_372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_88_i_reg_1024 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_79_i_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_79_i_reg_1029 : STD_LOGIC_VECTOR (0 downto 0);
    signal current_block_read_2_fu_772_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal current_block_read_2_reg_1033 : STD_LOGIC_VECTOR (1 downto 0);
    signal outElem_V_fu_861_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal outElem_V_reg_1064 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state7 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal inputBuf_0_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal inputBuf_0_V_ce0 : STD_LOGIC;
    signal inputBuf_0_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal inputBuf_0_V_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal inputBuf_0_V_ce1 : STD_LOGIC;
    signal inputBuf_0_V_we1 : STD_LOGIC;
    signal inputBuf_1_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal inputBuf_1_V_ce0 : STD_LOGIC;
    signal inputBuf_1_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal inputBuf_1_V_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal inputBuf_1_V_ce1 : STD_LOGIC;
    signal inputBuf_1_V_we1 : STD_LOGIC;
    signal inputBuf_2_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal inputBuf_2_V_ce0 : STD_LOGIC;
    signal inputBuf_2_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal inputBuf_2_V_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal inputBuf_2_V_ce1 : STD_LOGIC;
    signal inputBuf_2_V_we1 : STD_LOGIC;
    signal inputBuf_3_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal inputBuf_3_V_ce0 : STD_LOGIC;
    signal inputBuf_3_V_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal inputBuf_3_V_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal inputBuf_3_V_ce1 : STD_LOGIC;
    signal inputBuf_3_V_we1 : STD_LOGIC;
    signal tmp_77_i_fu_759_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_87_i_fu_777_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_72_i_fu_824_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal read_block_7_fu_94 : STD_LOGIC_VECTOR (31 downto 0);
    signal read_block_1_i_mid2_fu_460_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal read_block_3_cast_i_fu_686_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal read_block_fu_744_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ofm_y_1_i_fu_98 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ofm_y_2_i_fu_625_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_78_i_fu_543_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_80_i_fu_560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_82_i_fu_571_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_83_i_fu_591_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ofm_x_6_fu_102 : STD_LOGIC_VECTOR (31 downto 0);
    signal ofm_x_fu_585_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_y_6_fu_106 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_y_fu_503_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal inp_6_fu_110 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_inp_i_fu_617_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal inp_fu_728_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_x_6_fu_114 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_x_fu_554_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_simd_6_fu_118 : STD_LOGIC_VECTOR (31 downto 0);
    signal count_simd_fu_537_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_block_write_19_fu_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_block_write_4_fu_812_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_block_write_1_fu_848_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_line_7_fu_126 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_line_3_i_fu_670_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_366_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal counter_internal_blo_fu_130 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_i_fu_715_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3016_fu_785_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3011_fu_832_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_417_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_417_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal i_i_op_fu_440_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_3015_fu_513_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_3014_fu_509_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_74_i_fu_517_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_76_i_fu_523_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ofm_y_fu_605_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_84_i_fu_611_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_85_i_fu_646_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_86_i_fu_652_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3010_fu_468_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal read_block_1_cast_fu_664_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal read_block_1_fu_678_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal counter_internal_blo_24_fu_703_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_90_i_fu_709_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3013_fu_755_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_766_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal current_block_write_2_fu_792_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_89_i_fu_798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal current_block_write_3_fu_804_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal current_block_write_fu_836_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_81_i_fu_842_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_417_p00 : STD_LOGIC_VECTOR (45 downto 0);
    signal ap_condition_428 : BOOLEAN;
    signal ap_condition_440 : BOOLEAN;
    signal ap_condition_451 : BOOLEAN;
    signal ap_condition_462 : BOOLEAN;

    component BBJ_u96_cnvW1A1_mocq IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (45 downto 0) );
    end component;


    component BBJ_u96_cnvW1A1_mpcA IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component ConvolutionInputGkbM IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    inputBuf_0_V_U : component ConvolutionInputGkbM
    generic map (
        DataWidth => 32,
        AddressRange => 60,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_0_V_address0,
        ce0 => inputBuf_0_V_ce0,
        q0 => inputBuf_0_V_q0,
        address1 => inputBuf_0_V_address1,
        ce1 => inputBuf_0_V_ce1,
        we1 => inputBuf_0_V_we1,
        d1 => in_V_V_dout);

    inputBuf_1_V_U : component ConvolutionInputGkbM
    generic map (
        DataWidth => 32,
        AddressRange => 60,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_1_V_address0,
        ce0 => inputBuf_1_V_ce0,
        q0 => inputBuf_1_V_q0,
        address1 => inputBuf_1_V_address1,
        ce1 => inputBuf_1_V_ce1,
        we1 => inputBuf_1_V_we1,
        d1 => in_V_V_dout);

    inputBuf_2_V_U : component ConvolutionInputGkbM
    generic map (
        DataWidth => 32,
        AddressRange => 60,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_2_V_address0,
        ce0 => inputBuf_2_V_ce0,
        q0 => inputBuf_2_V_q0,
        address1 => inputBuf_2_V_address1,
        ce1 => inputBuf_2_V_ce1,
        we1 => inputBuf_2_V_we1,
        d1 => in_V_V_dout);

    inputBuf_3_V_U : component ConvolutionInputGkbM
    generic map (
        DataWidth => 32,
        AddressRange => 60,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => inputBuf_3_V_address0,
        ce0 => inputBuf_3_V_ce0,
        q0 => inputBuf_3_V_q0,
        address1 => inputBuf_3_V_address1,
        ce1 => inputBuf_3_V_ce1,
        we1 => inputBuf_3_V_we1,
        d1 => in_V_V_dout);

    BBJ_u96_cnvW1A1_mocq_U93 : component BBJ_u96_cnvW1A1_mocq
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 15,
        dout_WIDTH => 46)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_417_p0,
        din1 => grp_fu_417_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_417_p2);

    BBJ_u96_cnvW1A1_mpcA_U94 : component BBJ_u96_cnvW1A1_mpcA
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 2,
        dout_WIDTH => 32)
    port map (
        din0 => inputBuf_0_V_q0,
        din1 => inputBuf_1_V_q0,
        din2 => inputBuf_2_V_q0,
        din3 => inputBuf_3_V_q0,
        din4 => current_block_read_2_reg_1033,
        dout => outElem_V_fu_861_p6);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state7))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state7)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state7);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    count_simd_6_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_78_i_fu_543_p2 = ap_const_lv1_0) and (tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (tmp_73_i_fu_481_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                count_simd_6_fu_118 <= count_simd_fu_537_p2;
            elsif ((((tmp_80_i_fu_560_p2 = ap_const_lv1_0) and (tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (tmp_78_i_fu_543_p2 = ap_const_lv1_1) and (tmp_73_i_fu_481_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_82_i_fu_571_p2 = ap_const_lv1_0) and (tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (tmp_80_i_fu_560_p2 = ap_const_lv1_1) and (tmp_78_i_fu_543_p2 = ap_const_lv1_1) and (tmp_73_i_fu_481_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_83_i_fu_591_p2 = ap_const_lv1_0) and (tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (tmp_82_i_fu_571_p2 = ap_const_lv1_1) and (tmp_80_i_fu_560_p2 = ap_const_lv1_1) and (tmp_78_i_fu_543_p2 = ap_const_lv1_1) and (tmp_73_i_fu_481_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (tmp_83_i_fu_591_p2 = ap_const_lv1_1) and (tmp_82_i_fu_571_p2 = ap_const_lv1_1) and (tmp_80_i_fu_560_p2 = ap_const_lv1_1) and (tmp_78_i_fu_543_p2 = ap_const_lv1_1) and (tmp_73_i_fu_481_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                count_simd_6_fu_118 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    counter_internal_blo_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                counter_internal_blo_fu_130 <= p_i_fu_715_p3;
            elsif ((((tmp_79_i_fu_378_p2 = ap_const_lv1_1) and (tmp_i_2871_fu_472_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                counter_internal_blo_fu_130 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    current_block_write_19_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_79_i_reg_1029 = ap_const_lv1_1) and (tmp_i_2871_reg_990 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                current_block_write_19_fu_122 <= current_block_write_1_fu_848_p3;
            elsif (((or_cond_i_reg_1020 = ap_const_lv1_1) and (tmp_i_2871_reg_990 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                current_block_write_19_fu_122 <= current_block_write_4_fu_812_p3;
            elsif ((not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                current_block_write_19_fu_122 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    current_line_7_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_79_i_fu_378_p2 = ap_const_lv1_0) and (tmp_i_2871_fu_472_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                current_line_7_fu_126 <= grp_fu_366_p2;
            elsif (((tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (or_cond_i_fu_658_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                current_line_7_fu_126 <= current_line_3_i_fu_670_p3;
            elsif ((((tmp_79_i_fu_378_p2 = ap_const_lv1_1) and (tmp_i_2871_fu_472_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                current_line_7_fu_126 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    i_i_reg_312_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_fu_423_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                i_i_reg_312 <= i_fu_446_p3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                i_i_reg_312 <= ap_const_lv14_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_301_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_fu_423_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten_reg_301 <= indvar_flatten_next_fu_428_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                indvar_flatten_reg_301 <= ap_const_lv46_0;
            end if; 
        end if;
    end process;

    inp_6_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_2871_fu_472_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                inp_6_fu_110 <= inp_fu_728_p2;
            elsif (((tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (tmp_83_i_fu_591_p2 = ap_const_lv1_1) and (tmp_82_i_fu_571_p2 = ap_const_lv1_1) and (tmp_80_i_fu_560_p2 = ap_const_lv1_1) and (tmp_78_i_fu_543_p2 = ap_const_lv1_1) and (tmp_73_i_fu_481_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                inp_6_fu_110 <= p_inp_i_fu_617_p3;
            elsif ((not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                inp_6_fu_110 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    k_x_6_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_80_i_fu_560_p2 = ap_const_lv1_0) and (tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (tmp_78_i_fu_543_p2 = ap_const_lv1_1) and (tmp_73_i_fu_481_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                k_x_6_fu_114 <= k_x_fu_554_p2;
            elsif ((((tmp_82_i_fu_571_p2 = ap_const_lv1_0) and (tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (tmp_80_i_fu_560_p2 = ap_const_lv1_1) and (tmp_78_i_fu_543_p2 = ap_const_lv1_1) and (tmp_73_i_fu_481_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_83_i_fu_591_p2 = ap_const_lv1_0) and (tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (tmp_82_i_fu_571_p2 = ap_const_lv1_1) and (tmp_80_i_fu_560_p2 = ap_const_lv1_1) and (tmp_78_i_fu_543_p2 = ap_const_lv1_1) and (tmp_73_i_fu_481_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (tmp_83_i_fu_591_p2 = ap_const_lv1_1) and (tmp_82_i_fu_571_p2 = ap_const_lv1_1) and (tmp_80_i_fu_560_p2 = ap_const_lv1_1) and (tmp_78_i_fu_543_p2 = ap_const_lv1_1) and (tmp_73_i_fu_481_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                k_x_6_fu_114 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    k_y_6_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_82_i_fu_571_p2 = ap_const_lv1_0) and (tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (tmp_80_i_fu_560_p2 = ap_const_lv1_1) and (tmp_78_i_fu_543_p2 = ap_const_lv1_1) and (tmp_73_i_fu_481_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                k_y_6_fu_106 <= k_y_fu_503_p2;
            elsif ((((tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (tmp_82_i_fu_571_p2 = ap_const_lv1_1) and (tmp_80_i_fu_560_p2 = ap_const_lv1_1) and (tmp_78_i_fu_543_p2 = ap_const_lv1_1) and (tmp_73_i_fu_481_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                k_y_6_fu_106 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    ofm_x_6_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_83_i_fu_591_p2 = ap_const_lv1_0) and (tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (tmp_82_i_fu_571_p2 = ap_const_lv1_1) and (tmp_80_i_fu_560_p2 = ap_const_lv1_1) and (tmp_78_i_fu_543_p2 = ap_const_lv1_1) and (tmp_73_i_fu_481_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                ofm_x_6_fu_102 <= ofm_x_fu_585_p2;
            elsif ((((tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (tmp_83_i_fu_591_p2 = ap_const_lv1_1) and (tmp_82_i_fu_571_p2 = ap_const_lv1_1) and (tmp_80_i_fu_560_p2 = ap_const_lv1_1) and (tmp_78_i_fu_543_p2 = ap_const_lv1_1) and (tmp_73_i_fu_481_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                ofm_x_6_fu_102 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    ofm_y_1_i_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (tmp_83_i_fu_591_p2 = ap_const_lv1_1) and (tmp_82_i_fu_571_p2 = ap_const_lv1_1) and (tmp_80_i_fu_560_p2 = ap_const_lv1_1) and (tmp_78_i_fu_543_p2 = ap_const_lv1_1) and (tmp_73_i_fu_481_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                ofm_y_1_i_fu_98 <= p_ofm_y_2_i_fu_625_p3;
            elsif ((not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                ofm_y_1_i_fu_98 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    read_block_7_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_79_i_fu_378_p2 = ap_const_lv1_1) and (tmp_i_2871_fu_472_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                read_block_7_fu_94 <= read_block_fu_744_p2;
            elsif (((tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (or_cond_i_fu_658_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                read_block_7_fu_94 <= read_block_3_cast_i_fu_686_p1;
            elsif ((((tmp_79_i_fu_378_p2 = ap_const_lv1_0) and (tmp_i_2871_fu_472_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((or_cond_i_fu_658_p2 = ap_const_lv1_0) and (tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
                read_block_7_fu_94 <= read_block_1_i_mid2_fu_460_p3;
            elsif ((not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                read_block_7_fu_94 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                bound_reg_966 <= grp_fu_417_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_73_i_reg_994 = ap_const_lv1_1) and (tmp_i_2871_reg_990 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                current_block_read_2_reg_1033 <= current_block_read_2_fu_772_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (tmp_73_i_fu_481_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                current_line_in_bloc_reg_1003 <= current_line_in_bloc_fu_531_p2;
                tmp_3012_reg_998 <= tmp_3012_fu_499_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                exitcond_flatten_reg_971 <= exitcond_flatten_fu_423_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                numReps_read_reg_956 <= numReps_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                or_cond_i_reg_1020 <= or_cond_i_fu_658_p2;
                tmp_73_i_reg_994 <= tmp_73_i_fu_481_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_2871_reg_990_pp0_iter2_reg = ap_const_lv1_0) and (tmp_73_i_reg_994_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                outElem_V_reg_1064 <= outElem_V_fu_861_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((tmp_i_2871_fu_472_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (or_cond_i_fu_658_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then
                reg_390 <= current_line_7_fu_126;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                tmp_73_i_reg_994_pp0_iter2_reg <= tmp_73_i_reg_994;
                tmp_73_i_reg_994_pp0_iter3_reg <= tmp_73_i_reg_994_pp0_iter2_reg;
                tmp_i_2871_reg_990_pp0_iter2_reg <= tmp_i_2871_reg_990;
                tmp_i_2871_reg_990_pp0_iter3_reg <= tmp_i_2871_reg_990_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_2871_fu_472_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_79_i_reg_1029 <= tmp_79_i_fu_378_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_i_2871_fu_472_p2 = ap_const_lv1_0) and (or_cond_i_fu_658_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_88_i_reg_1024 <= tmp_88_i_fu_372_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_reg_971 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_i_2871_reg_990 <= tmp_i_2871_fu_472_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_fu_423_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_i_reg_980 <= tmp_i_fu_434_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, numReps_empty_n, numReps_out_full_n, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter1, exitcond_flatten_fu_423_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (exitcond_flatten_fu_423_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) and not(((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (exitcond_flatten_fu_423_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(6);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state12 <= ap_CS_fsm(7);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(in_V_V_empty_n, out_V_V_full_n, ap_enable_reg_pp0_iter2, tmp_i_2871_reg_990, ap_enable_reg_pp0_iter4, ap_predicate_op174_read_state9, ap_predicate_op228_write_state11)
    begin
                ap_block_pp0_stage0_01001 <= (((out_V_V_full_n = ap_const_logic_0) and (ap_predicate_op228_write_state11 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((in_V_V_empty_n = ap_const_logic_0) and (ap_predicate_op174_read_state9 = ap_const_boolean_1)) or ((tmp_i_2871_reg_990 = ap_const_lv1_1) and (in_V_V_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(in_V_V_empty_n, out_V_V_full_n, ap_enable_reg_pp0_iter2, tmp_i_2871_reg_990, ap_enable_reg_pp0_iter4, ap_predicate_op174_read_state9, ap_predicate_op228_write_state11)
    begin
                ap_block_pp0_stage0_11001 <= (((out_V_V_full_n = ap_const_logic_0) and (ap_predicate_op228_write_state11 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((in_V_V_empty_n = ap_const_logic_0) and (ap_predicate_op174_read_state9 = ap_const_boolean_1)) or ((tmp_i_2871_reg_990 = ap_const_lv1_1) and (in_V_V_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(in_V_V_empty_n, out_V_V_full_n, ap_enable_reg_pp0_iter2, tmp_i_2871_reg_990, ap_enable_reg_pp0_iter4, ap_predicate_op174_read_state9, ap_predicate_op228_write_state11)
    begin
                ap_block_pp0_stage0_subdone <= (((out_V_V_full_n = ap_const_logic_0) and (ap_predicate_op228_write_state11 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((in_V_V_empty_n = ap_const_logic_0) and (ap_predicate_op174_read_state9 = ap_const_boolean_1)) or ((tmp_i_2871_reg_990 = ap_const_lv1_1) and (in_V_V_empty_n = ap_const_logic_0)))));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, numReps_empty_n, numReps_out_full_n)
    begin
                ap_block_state1 <= ((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state10_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state11_pp0_stage0_iter4_assign_proc : process(out_V_V_full_n, ap_predicate_op228_write_state11)
    begin
                ap_block_state11_pp0_stage0_iter4 <= ((out_V_V_full_n = ap_const_logic_0) and (ap_predicate_op228_write_state11 = ap_const_boolean_1));
    end process;

        ap_block_state7_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state9_pp0_stage0_iter2_assign_proc : process(in_V_V_empty_n, tmp_i_2871_reg_990, ap_predicate_op174_read_state9)
    begin
                ap_block_state9_pp0_stage0_iter2 <= (((in_V_V_empty_n = ap_const_logic_0) and (ap_predicate_op174_read_state9 = ap_const_boolean_1)) or ((tmp_i_2871_reg_990 = ap_const_lv1_1) and (in_V_V_empty_n = ap_const_logic_0)));
    end process;


    ap_condition_428_assign_proc : process(tmp_i_2871_reg_990, or_cond_i_reg_1020, tmp_3016_fu_785_p1)
    begin
                ap_condition_428 <= ((or_cond_i_reg_1020 = ap_const_lv1_1) and (tmp_i_2871_reg_990 = ap_const_lv1_0) and (tmp_3016_fu_785_p1 = ap_const_lv2_0));
    end process;


    ap_condition_440_assign_proc : process(tmp_i_2871_reg_990, or_cond_i_reg_1020, tmp_3016_fu_785_p1)
    begin
                ap_condition_440 <= ((or_cond_i_reg_1020 = ap_const_lv1_1) and (tmp_i_2871_reg_990 = ap_const_lv1_0) and (tmp_3016_fu_785_p1 = ap_const_lv2_1));
    end process;


    ap_condition_451_assign_proc : process(tmp_i_2871_reg_990, or_cond_i_reg_1020, tmp_3016_fu_785_p1)
    begin
                ap_condition_451 <= ((or_cond_i_reg_1020 = ap_const_lv1_1) and (tmp_i_2871_reg_990 = ap_const_lv1_0) and (tmp_3016_fu_785_p1 = ap_const_lv2_2));
    end process;


    ap_condition_462_assign_proc : process(tmp_i_2871_reg_990, or_cond_i_reg_1020, tmp_3016_fu_785_p1)
    begin
                ap_condition_462 <= ((or_cond_i_reg_1020 = ap_const_lv1_1) and (tmp_i_2871_reg_990 = ap_const_lv1_0) and (tmp_3016_fu_785_p1 = ap_const_lv2_3));
    end process;


    ap_condition_pp0_exit_iter0_state7_assign_proc : process(exitcond_flatten_fu_423_p2)
    begin
        if ((exitcond_flatten_fu_423_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state7 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state7 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op174_read_state9_assign_proc : process(tmp_i_2871_reg_990, or_cond_i_reg_1020)
    begin
                ap_predicate_op174_read_state9 <= ((or_cond_i_reg_1020 = ap_const_lv1_1) and (tmp_i_2871_reg_990 = ap_const_lv1_0));
    end process;


    ap_predicate_op228_write_state11_assign_proc : process(tmp_i_2871_reg_990_pp0_iter3_reg, tmp_73_i_reg_994_pp0_iter3_reg)
    begin
                ap_predicate_op228_write_state11 <= ((tmp_i_2871_reg_990_pp0_iter3_reg = ap_const_lv1_0) and (tmp_73_i_reg_994_pp0_iter3_reg = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    count_simd_fu_537_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(count_simd_6_fu_118));
    counter_internal_blo_24_fu_703_p2 <= std_logic_vector(unsigned(counter_internal_blo_fu_130) + unsigned(ap_const_lv32_1));
    current_block_read_2_fu_772_p2 <= std_logic_vector(unsigned(tmp_fu_766_p2) + unsigned(tmp_3012_reg_998));
    current_block_write_1_fu_848_p3 <= 
        ap_const_lv32_0 when (tmp_81_i_fu_842_p2(0) = '1') else 
        current_block_write_fu_836_p2;
    current_block_write_2_fu_792_p2 <= std_logic_vector(unsigned(current_block_write_19_fu_122) + unsigned(ap_const_lv32_1));
    current_block_write_3_fu_804_p3 <= 
        ap_const_lv32_0 when (tmp_89_i_fu_798_p2(0) = '1') else 
        current_block_write_2_fu_792_p2;
    current_block_write_4_fu_812_p3 <= 
        current_block_write_3_fu_804_p3 when (tmp_88_i_reg_1024(0) = '1') else 
        current_block_write_19_fu_122;
    current_block_write_fu_836_p2 <= std_logic_vector(unsigned(current_block_write_19_fu_122) + unsigned(ap_const_lv32_1));
    current_line_3_i_fu_670_p3 <= 
        ap_const_lv32_0 when (tmp_88_i_fu_372_p2(0) = '1') else 
        grp_fu_366_p2;
    current_line_in_bloc_fu_531_p2 <= std_logic_vector(unsigned(tmp_76_i_fu_523_p3) + unsigned(count_simd_6_fu_118));
    exitcond_flatten_fu_423_p2 <= "1" when (indvar_flatten_reg_301 = bound_reg_966) else "0";
    grp_fu_366_p2 <= std_logic_vector(unsigned(current_line_7_fu_126) + unsigned(ap_const_lv32_1));
    grp_fu_417_p0 <= grp_fu_417_p00(32 - 1 downto 0);
    grp_fu_417_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(numReps_read_reg_956),46));
    grp_fu_417_p1 <= ap_const_lv46_37D4(15 - 1 downto 0);
    i_fu_446_p3 <= 
        ap_const_lv14_1 when (tmp_i_fu_434_p2(0) = '1') else 
        i_i_op_fu_440_p2;
    i_i_op_fu_440_p2 <= std_logic_vector(unsigned(i_i_reg_312) + unsigned(ap_const_lv14_1));

    in_V_V_blk_n_assign_proc : process(in_V_V_empty_n, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, tmp_i_2871_reg_990, or_cond_i_reg_1020)
    begin
        if ((((or_cond_i_reg_1020 = ap_const_lv1_1) and (tmp_i_2871_reg_990 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((tmp_i_2871_reg_990 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
            in_V_V_blk_n <= in_V_V_empty_n;
        else 
            in_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_V_V_read_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_2871_reg_990, ap_predicate_op174_read_state9, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_i_2871_reg_990 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_predicate_op174_read_state9 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            in_V_V_read <= ap_const_logic_1;
        else 
            in_V_V_read <= ap_const_logic_0;
        end if; 
    end process;

    indvar_flatten_next_fu_428_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_301) + unsigned(ap_const_lv46_1));
    inp_fu_728_p2 <= std_logic_vector(unsigned(inp_6_fu_110) + unsigned(ap_const_lv32_1));
    inputBuf_0_V_address0 <= tmp_77_i_fu_759_p1(6 - 1 downto 0);

    inputBuf_0_V_address1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, tmp_i_2871_reg_990, tmp_87_i_fu_777_p1, tmp_72_i_fu_824_p1, tmp_3011_fu_832_p1, ap_condition_428)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if (((tmp_i_2871_reg_990 = ap_const_lv1_1) and (tmp_3011_fu_832_p1 = ap_const_lv2_0))) then 
                inputBuf_0_V_address1 <= tmp_72_i_fu_824_p1(6 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_428)) then 
                inputBuf_0_V_address1 <= tmp_87_i_fu_777_p1(6 - 1 downto 0);
            else 
                inputBuf_0_V_address1 <= "XXXXXX";
            end if;
        else 
            inputBuf_0_V_address1 <= "XXXXXX";
        end if; 
    end process;


    inputBuf_0_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            inputBuf_0_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_0_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_2871_reg_990, or_cond_i_reg_1020, ap_block_pp0_stage0_11001, tmp_3016_fu_785_p1, tmp_3011_fu_832_p1)
    begin
        if ((((or_cond_i_reg_1020 = ap_const_lv1_1) and (tmp_i_2871_reg_990 = ap_const_lv1_0) and (tmp_3016_fu_785_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_2871_reg_990 = ap_const_lv1_1) and (tmp_3011_fu_832_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_0_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_0_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_0_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_2871_reg_990, or_cond_i_reg_1020, ap_block_pp0_stage0_11001, tmp_3016_fu_785_p1, tmp_3011_fu_832_p1)
    begin
        if ((((or_cond_i_reg_1020 = ap_const_lv1_1) and (tmp_i_2871_reg_990 = ap_const_lv1_0) and (tmp_3016_fu_785_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_2871_reg_990 = ap_const_lv1_1) and (tmp_3011_fu_832_p1 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_0_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_0_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    inputBuf_1_V_address0 <= tmp_77_i_fu_759_p1(6 - 1 downto 0);

    inputBuf_1_V_address1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, tmp_i_2871_reg_990, tmp_87_i_fu_777_p1, tmp_72_i_fu_824_p1, tmp_3011_fu_832_p1, ap_condition_440)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if (((tmp_i_2871_reg_990 = ap_const_lv1_1) and (tmp_3011_fu_832_p1 = ap_const_lv2_1))) then 
                inputBuf_1_V_address1 <= tmp_72_i_fu_824_p1(6 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_440)) then 
                inputBuf_1_V_address1 <= tmp_87_i_fu_777_p1(6 - 1 downto 0);
            else 
                inputBuf_1_V_address1 <= "XXXXXX";
            end if;
        else 
            inputBuf_1_V_address1 <= "XXXXXX";
        end if; 
    end process;


    inputBuf_1_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            inputBuf_1_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_1_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_2871_reg_990, or_cond_i_reg_1020, ap_block_pp0_stage0_11001, tmp_3016_fu_785_p1, tmp_3011_fu_832_p1)
    begin
        if ((((or_cond_i_reg_1020 = ap_const_lv1_1) and (tmp_i_2871_reg_990 = ap_const_lv1_0) and (tmp_3016_fu_785_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_2871_reg_990 = ap_const_lv1_1) and (tmp_3011_fu_832_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_1_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_1_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_1_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_2871_reg_990, or_cond_i_reg_1020, ap_block_pp0_stage0_11001, tmp_3016_fu_785_p1, tmp_3011_fu_832_p1)
    begin
        if ((((or_cond_i_reg_1020 = ap_const_lv1_1) and (tmp_i_2871_reg_990 = ap_const_lv1_0) and (tmp_3016_fu_785_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_2871_reg_990 = ap_const_lv1_1) and (tmp_3011_fu_832_p1 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_1_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_1_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    inputBuf_2_V_address0 <= tmp_77_i_fu_759_p1(6 - 1 downto 0);

    inputBuf_2_V_address1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, tmp_i_2871_reg_990, tmp_87_i_fu_777_p1, tmp_72_i_fu_824_p1, tmp_3011_fu_832_p1, ap_condition_451)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if (((tmp_i_2871_reg_990 = ap_const_lv1_1) and (tmp_3011_fu_832_p1 = ap_const_lv2_2))) then 
                inputBuf_2_V_address1 <= tmp_72_i_fu_824_p1(6 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_451)) then 
                inputBuf_2_V_address1 <= tmp_87_i_fu_777_p1(6 - 1 downto 0);
            else 
                inputBuf_2_V_address1 <= "XXXXXX";
            end if;
        else 
            inputBuf_2_V_address1 <= "XXXXXX";
        end if; 
    end process;


    inputBuf_2_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            inputBuf_2_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_2_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_2871_reg_990, or_cond_i_reg_1020, ap_block_pp0_stage0_11001, tmp_3016_fu_785_p1, tmp_3011_fu_832_p1)
    begin
        if ((((or_cond_i_reg_1020 = ap_const_lv1_1) and (tmp_i_2871_reg_990 = ap_const_lv1_0) and (tmp_3016_fu_785_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_2871_reg_990 = ap_const_lv1_1) and (tmp_3011_fu_832_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_2_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_2_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_2_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_2871_reg_990, or_cond_i_reg_1020, ap_block_pp0_stage0_11001, tmp_3016_fu_785_p1, tmp_3011_fu_832_p1)
    begin
        if ((((or_cond_i_reg_1020 = ap_const_lv1_1) and (tmp_i_2871_reg_990 = ap_const_lv1_0) and (tmp_3016_fu_785_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_2871_reg_990 = ap_const_lv1_1) and (tmp_3011_fu_832_p1 = ap_const_lv2_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_2_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_2_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    inputBuf_3_V_address0 <= tmp_77_i_fu_759_p1(6 - 1 downto 0);

    inputBuf_3_V_address1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, tmp_i_2871_reg_990, tmp_87_i_fu_777_p1, tmp_72_i_fu_824_p1, tmp_3011_fu_832_p1, ap_condition_462)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
            if (((tmp_i_2871_reg_990 = ap_const_lv1_1) and (tmp_3011_fu_832_p1 = ap_const_lv2_3))) then 
                inputBuf_3_V_address1 <= tmp_72_i_fu_824_p1(6 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_462)) then 
                inputBuf_3_V_address1 <= tmp_87_i_fu_777_p1(6 - 1 downto 0);
            else 
                inputBuf_3_V_address1 <= "XXXXXX";
            end if;
        else 
            inputBuf_3_V_address1 <= "XXXXXX";
        end if; 
    end process;


    inputBuf_3_V_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            inputBuf_3_V_ce0 <= ap_const_logic_1;
        else 
            inputBuf_3_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_3_V_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_2871_reg_990, or_cond_i_reg_1020, ap_block_pp0_stage0_11001, tmp_3016_fu_785_p1, tmp_3011_fu_832_p1)
    begin
        if ((((or_cond_i_reg_1020 = ap_const_lv1_1) and (tmp_i_2871_reg_990 = ap_const_lv1_0) and (tmp_3016_fu_785_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_2871_reg_990 = ap_const_lv1_1) and (tmp_3011_fu_832_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_3_V_ce1 <= ap_const_logic_1;
        else 
            inputBuf_3_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    inputBuf_3_V_we1_assign_proc : process(ap_enable_reg_pp0_iter2, tmp_i_2871_reg_990, or_cond_i_reg_1020, ap_block_pp0_stage0_11001, tmp_3016_fu_785_p1, tmp_3011_fu_832_p1)
    begin
        if ((((or_cond_i_reg_1020 = ap_const_lv1_1) and (tmp_i_2871_reg_990 = ap_const_lv1_0) and (tmp_3016_fu_785_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_i_2871_reg_990 = ap_const_lv1_1) and (tmp_3011_fu_832_p1 = ap_const_lv2_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            inputBuf_3_V_we1 <= ap_const_logic_1;
        else 
            inputBuf_3_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_x_fu_554_p2 <= std_logic_vector(unsigned(k_x_6_fu_114) + unsigned(ap_const_lv32_1));
    k_y_fu_503_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(k_y_6_fu_106));

    numReps_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, numReps_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numReps_blk_n <= numReps_empty_n;
        else 
            numReps_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    numReps_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, numReps_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numReps_out_blk_n <= numReps_out_full_n;
        else 
            numReps_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    numReps_out_din <= numReps_dout;

    numReps_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, numReps_empty_n, numReps_out_full_n)
    begin
        if ((not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numReps_out_write <= ap_const_logic_1;
        else 
            numReps_out_write <= ap_const_logic_0;
        end if; 
    end process;


    numReps_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, numReps_empty_n, numReps_out_full_n)
    begin
        if ((not(((numReps_out_full_n = ap_const_logic_0) or (numReps_empty_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            numReps_read <= ap_const_logic_1;
        else 
            numReps_read <= ap_const_logic_0;
        end if; 
    end process;

    ofm_x_fu_585_p2 <= std_logic_vector(unsigned(ofm_x_6_fu_102) + unsigned(ap_const_lv32_1));
    ofm_y_fu_605_p2 <= std_logic_vector(unsigned(ofm_y_1_i_fu_98) + unsigned(ap_const_lv32_1));
    or_cond_i_fu_658_p2 <= (tmp_86_i_fu_652_p2 and tmp_85_i_fu_646_p2);

    out_V_V_blk_n_assign_proc : process(out_V_V_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter4, tmp_i_2871_reg_990_pp0_iter3_reg, tmp_73_i_reg_994_pp0_iter3_reg)
    begin
        if (((tmp_i_2871_reg_990_pp0_iter3_reg = ap_const_lv1_0) and (tmp_73_i_reg_994_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            out_V_V_blk_n <= out_V_V_full_n;
        else 
            out_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_V_V_din <= outElem_V_reg_1064;

    out_V_V_write_assign_proc : process(ap_enable_reg_pp0_iter4, ap_predicate_op228_write_state11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_predicate_op228_write_state11 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            out_V_V_write <= ap_const_logic_1;
        else 
            out_V_V_write <= ap_const_logic_0;
        end if; 
    end process;

    p_i_fu_715_p3 <= 
        ap_const_lv32_0 when (tmp_90_i_fu_709_p2(0) = '1') else 
        counter_internal_blo_24_fu_703_p2;
    p_inp_i_fu_617_p3 <= 
        ap_const_lv32_0 when (tmp_84_i_fu_611_p2(0) = '1') else 
        inp_6_fu_110;
    p_ofm_y_2_i_fu_625_p3 <= 
        ap_const_lv32_0 when (tmp_84_i_fu_611_p2(0) = '1') else 
        ofm_y_fu_605_p2;
    read_block_1_cast_fu_664_p2 <= std_logic_vector(unsigned(tmp_3010_fu_468_p1) + unsigned(ap_const_lv5_1));
    read_block_1_fu_678_p3 <= 
        read_block_1_cast_fu_664_p2 when (tmp_88_i_fu_372_p2(0) = '1') else 
        tmp_3010_fu_468_p1;
    read_block_1_i_mid2_fu_460_p3 <= 
        ap_const_lv32_0 when (tmp_i_reg_980(0) = '1') else 
        read_block_7_fu_94;
    read_block_3_cast_i_fu_686_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(read_block_1_fu_678_p3),32));
    read_block_fu_744_p2 <= std_logic_vector(unsigned(read_block_1_i_mid2_fu_460_p3) + unsigned(ap_const_lv32_1));
    tmp_3010_fu_468_p1 <= read_block_1_i_mid2_fu_460_p3(5 - 1 downto 0);
    tmp_3011_fu_832_p1 <= current_block_write_19_fu_122(2 - 1 downto 0);
    tmp_3012_fu_499_p1 <= k_y_6_fu_106(2 - 1 downto 0);
    tmp_3013_fu_755_p1 <= current_block_write_19_fu_122(2 - 1 downto 0);
    tmp_3014_fu_509_p1 <= k_x_6_fu_114(31 - 1 downto 0);
    tmp_3015_fu_513_p1 <= ofm_x_6_fu_102(31 - 1 downto 0);
    tmp_3016_fu_785_p1 <= current_block_write_19_fu_122(2 - 1 downto 0);
    tmp_72_i_fu_824_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_390),64));
    tmp_73_i_fu_481_p2 <= "1" when (unsigned(counter_internal_blo_fu_130) < unsigned(ap_const_lv32_1F7)) else "0";
    tmp_74_i_fu_517_p2 <= std_logic_vector(unsigned(tmp_3015_fu_513_p1) + unsigned(tmp_3014_fu_509_p1));
    tmp_76_i_fu_523_p3 <= (tmp_74_i_fu_517_p2 & ap_const_lv1_0);
    tmp_77_i_fu_759_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(current_line_in_bloc_reg_1003),64));
    tmp_78_i_fu_543_p2 <= "1" when (count_simd_fu_537_p2 = ap_const_lv32_2) else "0";
    tmp_79_i_fu_378_p2 <= "1" when (grp_fu_366_p2 = ap_const_lv32_3C) else "0";
    tmp_80_i_fu_560_p2 <= "1" when (k_x_fu_554_p2 = ap_const_lv32_3) else "0";
    tmp_81_i_fu_842_p2 <= "1" when (current_block_write_fu_836_p2 = ap_const_lv32_4) else "0";
    tmp_82_i_fu_571_p2 <= "1" when (k_y_fu_503_p2 = ap_const_lv32_3) else "0";
    tmp_83_i_fu_591_p2 <= "1" when (ofm_x_fu_585_p2 = ap_const_lv32_1C) else "0";
    tmp_84_i_fu_611_p2 <= "1" when (ofm_y_fu_605_p2 = ap_const_lv32_1C) else "0";
    tmp_85_i_fu_646_p2 <= "1" when (unsigned(counter_internal_blo_fu_130) < unsigned(ap_const_lv32_3B)) else "0";
    tmp_86_i_fu_652_p2 <= "1" when (unsigned(read_block_1_i_mid2_fu_460_p3) < unsigned(ap_const_lv32_1E)) else "0";
    tmp_87_i_fu_777_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_390),64));
    tmp_88_i_fu_372_p2 <= "1" when (grp_fu_366_p2 = ap_const_lv32_3C) else "0";
    tmp_89_i_fu_798_p2 <= "1" when (current_block_write_2_fu_792_p2 = ap_const_lv32_4) else "0";
    tmp_90_i_fu_709_p2 <= "1" when (counter_internal_blo_24_fu_703_p2 = ap_const_lv32_1F7) else "0";
    tmp_fu_766_p2 <= std_logic_vector(unsigned(ap_const_lv2_1) + unsigned(tmp_3013_fu_755_p1));
    tmp_i_2871_fu_472_p2 <= "1" when (unsigned(inp_6_fu_110) < unsigned(ap_const_lv32_B4)) else "0";
    tmp_i_fu_434_p2 <= "1" when (i_i_reg_312 = ap_const_lv14_37D4) else "0";
end behav;
