// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ConvolutionInputGene_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_V_V_dout,
        in_V_V_empty_n,
        in_V_V_read,
        out_V_V_din,
        out_V_V_full_n,
        out_V_V_write,
        numReps_dout,
        numReps_empty_n,
        numReps_read,
        numReps_out_din,
        numReps_out_full_n,
        numReps_out_write
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_pp0_stage0 = 8'd64;
parameter    ap_ST_fsm_state12 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [63:0] in_V_V_dout;
input   in_V_V_empty_n;
output   in_V_V_read;
output  [63:0] out_V_V_din;
input   out_V_V_full_n;
output   out_V_V_write;
input  [31:0] numReps_dout;
input   numReps_empty_n;
output   numReps_read;
output  [31:0] numReps_out_din;
input   numReps_out_full_n;
output   numReps_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_V_V_read;
reg out_V_V_write;
reg numReps_read;
reg numReps_out_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in_V_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_i_3621_reg_988;
reg   [0:0] or_cond_i_reg_1018;
reg    out_V_V_blk_n;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] tmp_i_3621_reg_988_pp0_iter3_reg;
reg   [0:0] tmp_170_i_reg_992;
reg   [0:0] tmp_170_i_reg_992_pp0_iter3_reg;
reg    numReps_blk_n;
reg    numReps_out_blk_n;
reg   [43:0] indvar_flatten_reg_299;
reg   [11:0] i_i_reg_310;
reg   [31:0] reg_388;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_state7_pp0_stage0_iter0;
wire    ap_block_state8_pp0_stage0_iter1;
reg    ap_predicate_op174_read_state9;
reg    ap_block_state9_pp0_stage0_iter2;
wire    ap_block_state10_pp0_stage0_iter3;
reg    ap_predicate_op228_write_state11;
reg    ap_block_state11_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_i_3621_fu_470_p2;
wire   [0:0] or_cond_i_fu_656_p2;
reg   [31:0] numReps_read_reg_954;
reg    ap_block_state1;
wire    ap_CS_fsm_state2;
wire   [43:0] grp_fu_415_p2;
reg   [43:0] bound_reg_964;
wire    ap_CS_fsm_state6;
wire   [0:0] exitcond_flatten_fu_421_p2;
reg   [0:0] exitcond_flatten_reg_969;
wire   [43:0] indvar_flatten_next_fu_426_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] tmp_i_fu_432_p2;
reg   [0:0] tmp_i_reg_978;
wire   [11:0] i_fu_444_p3;
reg   [0:0] tmp_i_3621_reg_988_pp0_iter2_reg;
wire   [0:0] tmp_170_i_fu_479_p2;
reg   [0:0] tmp_170_i_reg_992_pp0_iter2_reg;
wire   [1:0] tmp_2365_fu_497_p1;
reg   [1:0] tmp_2365_reg_996;
wire   [31:0] current_line_in_bloc_fu_529_p2;
reg   [31:0] current_line_in_bloc_reg_1001;
wire   [0:0] tmp_185_i_fu_370_p2;
reg   [0:0] tmp_185_i_reg_1022;
wire   [0:0] tmp_176_i_fu_376_p2;
reg   [0:0] tmp_176_i_reg_1027;
wire   [1:0] current_block_read_fu_770_p2;
reg   [1:0] current_block_read_reg_1031;
wire   [63:0] outElem_V_fu_859_p6;
reg   [63:0] outElem_V_reg_1062;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state7;
reg    ap_enable_reg_pp0_iter3;
wire   [5:0] inputBuf_0_V_address0;
reg    inputBuf_0_V_ce0;
wire   [63:0] inputBuf_0_V_q0;
reg   [5:0] inputBuf_0_V_address1;
reg    inputBuf_0_V_ce1;
reg    inputBuf_0_V_we1;
wire   [5:0] inputBuf_1_V_address0;
reg    inputBuf_1_V_ce0;
wire   [63:0] inputBuf_1_V_q0;
reg   [5:0] inputBuf_1_V_address1;
reg    inputBuf_1_V_ce1;
reg    inputBuf_1_V_we1;
wire   [5:0] inputBuf_2_V_address0;
reg    inputBuf_2_V_ce0;
wire   [63:0] inputBuf_2_V_q0;
reg   [5:0] inputBuf_2_V_address1;
reg    inputBuf_2_V_ce1;
reg    inputBuf_2_V_we1;
wire   [5:0] inputBuf_3_V_address0;
reg    inputBuf_3_V_ce0;
wire   [63:0] inputBuf_3_V_q0;
reg   [5:0] inputBuf_3_V_address1;
reg    inputBuf_3_V_ce1;
reg    inputBuf_3_V_we1;
wire   [63:0] tmp_174_i_fu_757_p1;
wire   [63:0] tmp_184_i_fu_775_p1;
wire   [63:0] tmp_169_i_fu_822_p1;
reg    ap_block_pp0_stage0_01001;
reg   [31:0] read_block_2_fu_92;
wire   [31:0] read_block_1_i_mid2_fu_458_p3;
wire   [31:0] read_block_3_cast_i_fu_684_p1;
wire   [31:0] read_block_fu_742_p2;
reg   [31:0] ofm_y_1_i_fu_96;
wire   [31:0] p_ofm_y_9_i_fu_623_p3;
wire   [0:0] tmp_175_i_fu_541_p2;
wire   [0:0] tmp_177_i_fu_558_p2;
wire   [0:0] tmp_179_i_fu_569_p2;
wire   [0:0] tmp_180_i_fu_589_p2;
reg   [31:0] ofm_x_1_fu_100;
wire   [31:0] ofm_x_fu_583_p2;
reg   [31:0] k_y_1_fu_104;
wire   [31:0] k_y_fu_501_p2;
reg   [31:0] inp_1_fu_108;
wire   [31:0] p_inp_1_i_fu_615_p3;
wire   [31:0] inp_fu_726_p2;
reg   [31:0] k_x_1_fu_112;
wire   [31:0] k_x_fu_552_p2;
reg   [31:0] count_simd_1_fu_116;
wire   [31:0] count_simd_fu_535_p2;
reg   [31:0] current_block_write_5_fu_120;
wire   [31:0] current_block_write_4_3618_fu_810_p3;
wire   [31:0] current_block_write_1_3615_fu_846_p3;
reg   [31:0] current_line_2_fu_124;
wire   [31:0] current_line_3_i_fu_668_p3;
wire   [31:0] grp_fu_364_p2;
reg   [31:0] counter_internal_blo_fu_128;
wire   [31:0] p_i_fu_713_p3;
wire   [1:0] tmp_2369_fu_783_p1;
wire   [1:0] tmp_2364_fu_830_p1;
wire   [31:0] grp_fu_415_p0;
wire   [12:0] grp_fu_415_p1;
wire   [11:0] i_i_op_fu_438_p2;
wire   [29:0] tmp_2368_fu_511_p1;
wire   [29:0] tmp_2367_fu_507_p1;
wire   [29:0] tmp_171_i_fu_515_p2;
wire   [31:0] tmp_173_i_fu_521_p3;
wire   [31:0] ofm_y_fu_603_p2;
wire   [0:0] tmp_181_i_fu_609_p2;
wire   [0:0] tmp_182_i_fu_644_p2;
wire   [0:0] tmp_183_i_fu_650_p2;
wire   [3:0] tmp_2363_fu_466_p1;
wire   [3:0] read_block_6_cast_fu_662_p2;
wire   [3:0] read_block_1_fu_676_p3;
wire   [31:0] counter_internal_blo_4_fu_701_p2;
wire   [0:0] tmp_187_i_fu_707_p2;
wire   [1:0] tmp_2366_fu_753_p1;
wire   [1:0] tmp_fu_764_p2;
wire   [31:0] current_block_write_2_3616_fu_790_p2;
wire   [0:0] tmp_186_i_fu_796_p2;
wire   [31:0] current_block_write_3_3617_fu_802_p3;
wire   [31:0] current_block_write_fu_834_p2;
wire   [0:0] tmp_178_i_fu_840_p2;
wire    ap_CS_fsm_state12;
reg   [7:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [43:0] grp_fu_415_p00;
reg    ap_condition_428;
reg    ap_condition_440;
reg    ap_condition_451;
reg    ap_condition_462;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

ConvolutionInputGbzo #(
    .DataWidth( 64 ),
    .AddressRange( 48 ),
    .AddressWidth( 6 ))
inputBuf_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_0_V_address0),
    .ce0(inputBuf_0_V_ce0),
    .q0(inputBuf_0_V_q0),
    .address1(inputBuf_0_V_address1),
    .ce1(inputBuf_0_V_ce1),
    .we1(inputBuf_0_V_we1),
    .d1(in_V_V_dout)
);

ConvolutionInputGbzo #(
    .DataWidth( 64 ),
    .AddressRange( 48 ),
    .AddressWidth( 6 ))
inputBuf_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_1_V_address0),
    .ce0(inputBuf_1_V_ce0),
    .q0(inputBuf_1_V_q0),
    .address1(inputBuf_1_V_address1),
    .ce1(inputBuf_1_V_ce1),
    .we1(inputBuf_1_V_we1),
    .d1(in_V_V_dout)
);

ConvolutionInputGbzo #(
    .DataWidth( 64 ),
    .AddressRange( 48 ),
    .AddressWidth( 6 ))
inputBuf_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_2_V_address0),
    .ce0(inputBuf_2_V_ce0),
    .q0(inputBuf_2_V_q0),
    .address1(inputBuf_2_V_address1),
    .ce1(inputBuf_2_V_ce1),
    .we1(inputBuf_2_V_we1),
    .d1(in_V_V_dout)
);

ConvolutionInputGbzo #(
    .DataWidth( 64 ),
    .AddressRange( 48 ),
    .AddressWidth( 6 ))
inputBuf_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_3_V_address0),
    .ce0(inputBuf_3_V_ce0),
    .q0(inputBuf_3_V_q0),
    .address1(inputBuf_3_V_address1),
    .ce1(inputBuf_3_V_ce1),
    .we1(inputBuf_3_V_we1),
    .d1(in_V_V_dout)
);

BBJ_u96_cnvW1A2_mbyn #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 44 ))
BBJ_u96_cnvW1A2_mbyn_U305(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_415_p0),
    .din1(grp_fu_415_p1),
    .ce(1'b1),
    .dout(grp_fu_415_p2)
);

BBJ_u96_cnvW1A2_mocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .din2_WIDTH( 64 ),
    .din3_WIDTH( 64 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 64 ))
BBJ_u96_cnvW1A2_mocq_U306(
    .din0(inputBuf_0_V_q0),
    .din1(inputBuf_1_V_q0),
    .din2(inputBuf_2_V_q0),
    .din3(inputBuf_3_V_q0),
    .din4(current_block_read_reg_1031),
    .dout(outElem_V_fu_859_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state12)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state7))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state7)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state7);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_175_i_fu_541_p2 == 1'd0) & (tmp_i_3621_fu_470_p2 == 1'd0) & (tmp_170_i_fu_479_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        count_simd_1_fu_116 <= count_simd_fu_535_p2;
    end else if ((((tmp_177_i_fu_558_p2 == 1'd0) & (tmp_i_3621_fu_470_p2 == 1'd0) & (tmp_175_i_fu_541_p2 == 1'd1) & (tmp_170_i_fu_479_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_179_i_fu_569_p2 == 1'd0) & (tmp_i_3621_fu_470_p2 == 1'd0) & (tmp_177_i_fu_558_p2 == 1'd1) & (tmp_175_i_fu_541_p2 == 1'd1) & (tmp_170_i_fu_479_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_180_i_fu_589_p2 == 1'd0) & (tmp_i_3621_fu_470_p2 == 1'd0) & (tmp_179_i_fu_569_p2 == 1'd1) & (tmp_177_i_fu_558_p2 == 1'd1) & (tmp_175_i_fu_541_p2 == 1'd1) & (tmp_170_i_fu_479_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_3621_fu_470_p2 == 1'd0) & (tmp_180_i_fu_589_p2 == 1'd1) & (tmp_179_i_fu_569_p2 == 1'd1) & (tmp_177_i_fu_558_p2 == 1'd1) & (tmp_175_i_fu_541_p2 == 1'd1) & (tmp_170_i_fu_479_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        count_simd_1_fu_116 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_3621_fu_470_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        counter_internal_blo_fu_128 <= p_i_fu_713_p3;
    end else if ((((tmp_176_i_fu_376_p2 == 1'd1) & (tmp_i_3621_fu_470_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        counter_internal_blo_fu_128 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_176_i_reg_1027 == 1'd1) & (tmp_i_3621_reg_988 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_block_write_5_fu_120 <= current_block_write_1_3615_fu_846_p3;
    end else if (((or_cond_i_reg_1018 == 1'd1) & (tmp_i_3621_reg_988 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_block_write_5_fu_120 <= current_block_write_4_3618_fu_810_p3;
    end else if ((~((numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        current_block_write_5_fu_120 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_176_i_fu_376_p2 == 1'd0) & (tmp_i_3621_fu_470_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_line_2_fu_124 <= grp_fu_364_p2;
    end else if (((tmp_i_3621_fu_470_p2 == 1'd0) & (or_cond_i_fu_656_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_line_2_fu_124 <= current_line_3_i_fu_668_p3;
    end else if ((((tmp_176_i_fu_376_p2 == 1'd1) & (tmp_i_3621_fu_470_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        current_line_2_fu_124 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_421_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_i_reg_310 <= i_fu_444_p3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        i_i_reg_310 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_421_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_reg_299 <= indvar_flatten_next_fu_426_p2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        indvar_flatten_reg_299 <= 44'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_3621_fu_470_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inp_1_fu_108 <= inp_fu_726_p2;
    end else if (((tmp_i_3621_fu_470_p2 == 1'd0) & (tmp_180_i_fu_589_p2 == 1'd1) & (tmp_179_i_fu_569_p2 == 1'd1) & (tmp_177_i_fu_558_p2 == 1'd1) & (tmp_175_i_fu_541_p2 == 1'd1) & (tmp_170_i_fu_479_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inp_1_fu_108 <= p_inp_1_i_fu_615_p3;
    end else if ((~((numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        inp_1_fu_108 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_177_i_fu_558_p2 == 1'd0) & (tmp_i_3621_fu_470_p2 == 1'd0) & (tmp_175_i_fu_541_p2 == 1'd1) & (tmp_170_i_fu_479_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_x_1_fu_112 <= k_x_fu_552_p2;
    end else if ((((tmp_179_i_fu_569_p2 == 1'd0) & (tmp_i_3621_fu_470_p2 == 1'd0) & (tmp_177_i_fu_558_p2 == 1'd1) & (tmp_175_i_fu_541_p2 == 1'd1) & (tmp_170_i_fu_479_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_180_i_fu_589_p2 == 1'd0) & (tmp_i_3621_fu_470_p2 == 1'd0) & (tmp_179_i_fu_569_p2 == 1'd1) & (tmp_177_i_fu_558_p2 == 1'd1) & (tmp_175_i_fu_541_p2 == 1'd1) & (tmp_170_i_fu_479_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_3621_fu_470_p2 == 1'd0) & (tmp_180_i_fu_589_p2 == 1'd1) & (tmp_179_i_fu_569_p2 == 1'd1) & (tmp_177_i_fu_558_p2 == 1'd1) & (tmp_175_i_fu_541_p2 == 1'd1) & (tmp_170_i_fu_479_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        k_x_1_fu_112 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_179_i_fu_569_p2 == 1'd0) & (tmp_i_3621_fu_470_p2 == 1'd0) & (tmp_177_i_fu_558_p2 == 1'd1) & (tmp_175_i_fu_541_p2 == 1'd1) & (tmp_170_i_fu_479_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_y_1_fu_104 <= k_y_fu_501_p2;
    end else if ((((tmp_i_3621_fu_470_p2 == 1'd0) & (tmp_179_i_fu_569_p2 == 1'd1) & (tmp_177_i_fu_558_p2 == 1'd1) & (tmp_175_i_fu_541_p2 == 1'd1) & (tmp_170_i_fu_479_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        k_y_1_fu_104 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_180_i_fu_589_p2 == 1'd0) & (tmp_i_3621_fu_470_p2 == 1'd0) & (tmp_179_i_fu_569_p2 == 1'd1) & (tmp_177_i_fu_558_p2 == 1'd1) & (tmp_175_i_fu_541_p2 == 1'd1) & (tmp_170_i_fu_479_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ofm_x_1_fu_100 <= ofm_x_fu_583_p2;
    end else if ((((tmp_i_3621_fu_470_p2 == 1'd0) & (tmp_180_i_fu_589_p2 == 1'd1) & (tmp_179_i_fu_569_p2 == 1'd1) & (tmp_177_i_fu_558_p2 == 1'd1) & (tmp_175_i_fu_541_p2 == 1'd1) & (tmp_170_i_fu_479_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~((numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        ofm_x_1_fu_100 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_3621_fu_470_p2 == 1'd0) & (tmp_180_i_fu_589_p2 == 1'd1) & (tmp_179_i_fu_569_p2 == 1'd1) & (tmp_177_i_fu_558_p2 == 1'd1) & (tmp_175_i_fu_541_p2 == 1'd1) & (tmp_170_i_fu_479_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ofm_y_1_i_fu_96 <= p_ofm_y_9_i_fu_623_p3;
    end else if ((~((numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ofm_y_1_i_fu_96 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_176_i_fu_376_p2 == 1'd1) & (tmp_i_3621_fu_470_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        read_block_2_fu_92 <= read_block_fu_742_p2;
    end else if (((tmp_i_3621_fu_470_p2 == 1'd0) & (or_cond_i_fu_656_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        read_block_2_fu_92 <= read_block_3_cast_i_fu_684_p1;
    end else if ((((tmp_176_i_fu_376_p2 == 1'd0) & (tmp_i_3621_fu_470_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((or_cond_i_fu_656_p2 == 1'd0) & (tmp_i_3621_fu_470_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        read_block_2_fu_92 <= read_block_1_i_mid2_fu_458_p3;
    end else if ((~((numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        read_block_2_fu_92 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        bound_reg_964 <= grp_fu_415_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_170_i_reg_992 == 1'd1) & (tmp_i_3621_reg_988 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_block_read_reg_1031 <= current_block_read_fu_770_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_3621_fu_470_p2 == 1'd0) & (tmp_170_i_fu_479_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        current_line_in_bloc_reg_1001 <= current_line_in_bloc_fu_529_p2;
        tmp_2365_reg_996 <= tmp_2365_fu_497_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond_flatten_reg_969 <= exitcond_flatten_fu_421_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_read_reg_954 <= numReps_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_3621_fu_470_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_cond_i_reg_1018 <= or_cond_i_fu_656_p2;
        tmp_170_i_reg_992 <= tmp_170_i_fu_479_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_3621_reg_988_pp0_iter2_reg == 1'd0) & (tmp_170_i_reg_992_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outElem_V_reg_1062 <= outElem_V_fu_859_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((((tmp_i_3621_fu_470_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_3621_fu_470_p2 == 1'd0) & (or_cond_i_fu_656_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        reg_388 <= current_line_2_fu_124;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        tmp_170_i_reg_992_pp0_iter2_reg <= tmp_170_i_reg_992;
        tmp_170_i_reg_992_pp0_iter3_reg <= tmp_170_i_reg_992_pp0_iter2_reg;
        tmp_i_3621_reg_988_pp0_iter2_reg <= tmp_i_3621_reg_988;
        tmp_i_3621_reg_988_pp0_iter3_reg <= tmp_i_3621_reg_988_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_3621_fu_470_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_176_i_reg_1027 <= tmp_176_i_fu_376_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_3621_fu_470_p2 == 1'd0) & (or_cond_i_fu_656_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_185_i_reg_1022 <= tmp_185_i_fu_370_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_969 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_i_3621_reg_988 <= tmp_i_3621_fu_470_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_421_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_i_reg_978 <= tmp_i_fu_432_p2;
    end
end

always @ (*) begin
    if ((exitcond_flatten_fu_421_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state7 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state7 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1018 == 1'd1) & (tmp_i_3621_reg_988 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_i_3621_reg_988 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        in_V_V_blk_n = in_V_V_empty_n;
    end else begin
        in_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((tmp_i_3621_reg_988 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_predicate_op174_read_state9 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        in_V_V_read = 1'b1;
    end else begin
        in_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((tmp_i_3621_reg_988 == 1'd1) & (tmp_2364_fu_830_p1 == 2'd0))) begin
            inputBuf_0_V_address1 = tmp_169_i_fu_822_p1;
        end else if ((1'b1 == ap_condition_428)) begin
            inputBuf_0_V_address1 = tmp_184_i_fu_775_p1;
        end else begin
            inputBuf_0_V_address1 = 'bx;
        end
    end else begin
        inputBuf_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_0_V_ce0 = 1'b1;
    end else begin
        inputBuf_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1018 == 1'd1) & (tmp_i_3621_reg_988 == 1'd0) & (tmp_2369_fu_783_p1 == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_3621_reg_988 == 1'd1) & (tmp_2364_fu_830_p1 == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_0_V_ce1 = 1'b1;
    end else begin
        inputBuf_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1018 == 1'd1) & (tmp_i_3621_reg_988 == 1'd0) & (tmp_2369_fu_783_p1 == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_3621_reg_988 == 1'd1) & (tmp_2364_fu_830_p1 == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_0_V_we1 = 1'b1;
    end else begin
        inputBuf_0_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((tmp_i_3621_reg_988 == 1'd1) & (tmp_2364_fu_830_p1 == 2'd1))) begin
            inputBuf_1_V_address1 = tmp_169_i_fu_822_p1;
        end else if ((1'b1 == ap_condition_440)) begin
            inputBuf_1_V_address1 = tmp_184_i_fu_775_p1;
        end else begin
            inputBuf_1_V_address1 = 'bx;
        end
    end else begin
        inputBuf_1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_1_V_ce0 = 1'b1;
    end else begin
        inputBuf_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1018 == 1'd1) & (tmp_i_3621_reg_988 == 1'd0) & (tmp_2369_fu_783_p1 == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_3621_reg_988 == 1'd1) & (tmp_2364_fu_830_p1 == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_1_V_ce1 = 1'b1;
    end else begin
        inputBuf_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1018 == 1'd1) & (tmp_i_3621_reg_988 == 1'd0) & (tmp_2369_fu_783_p1 == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_3621_reg_988 == 1'd1) & (tmp_2364_fu_830_p1 == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_1_V_we1 = 1'b1;
    end else begin
        inputBuf_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((tmp_i_3621_reg_988 == 1'd1) & (tmp_2364_fu_830_p1 == 2'd2))) begin
            inputBuf_2_V_address1 = tmp_169_i_fu_822_p1;
        end else if ((1'b1 == ap_condition_451)) begin
            inputBuf_2_V_address1 = tmp_184_i_fu_775_p1;
        end else begin
            inputBuf_2_V_address1 = 'bx;
        end
    end else begin
        inputBuf_2_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_2_V_ce0 = 1'b1;
    end else begin
        inputBuf_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1018 == 1'd1) & (tmp_i_3621_reg_988 == 1'd0) & (tmp_2369_fu_783_p1 == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_3621_reg_988 == 1'd1) & (tmp_2364_fu_830_p1 == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_2_V_ce1 = 1'b1;
    end else begin
        inputBuf_2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1018 == 1'd1) & (tmp_i_3621_reg_988 == 1'd0) & (tmp_2369_fu_783_p1 == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_3621_reg_988 == 1'd1) & (tmp_2364_fu_830_p1 == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_2_V_we1 = 1'b1;
    end else begin
        inputBuf_2_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if (((tmp_i_3621_reg_988 == 1'd1) & (tmp_2364_fu_830_p1 == 2'd3))) begin
            inputBuf_3_V_address1 = tmp_169_i_fu_822_p1;
        end else if ((1'b1 == ap_condition_462)) begin
            inputBuf_3_V_address1 = tmp_184_i_fu_775_p1;
        end else begin
            inputBuf_3_V_address1 = 'bx;
        end
    end else begin
        inputBuf_3_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inputBuf_3_V_ce0 = 1'b1;
    end else begin
        inputBuf_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1018 == 1'd1) & (tmp_i_3621_reg_988 == 1'd0) & (tmp_2369_fu_783_p1 == 2'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_3621_reg_988 == 1'd1) & (tmp_2364_fu_830_p1 == 2'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_3_V_ce1 = 1'b1;
    end else begin
        inputBuf_3_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_reg_1018 == 1'd1) & (tmp_i_3621_reg_988 == 1'd0) & (tmp_2369_fu_783_p1 == 2'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_i_3621_reg_988 == 1'd1) & (tmp_2364_fu_830_p1 == 2'd3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        inputBuf_3_V_we1 = 1'b1;
    end else begin
        inputBuf_3_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_blk_n = numReps_empty_n;
    end else begin
        numReps_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_out_blk_n = numReps_out_full_n;
    end else begin
        numReps_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_out_write = 1'b1;
    end else begin
        numReps_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        numReps_read = 1'b1;
    end else begin
        numReps_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_3621_reg_988_pp0_iter3_reg == 1'd0) & (tmp_170_i_reg_992_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        out_V_V_blk_n = out_V_V_full_n;
    end else begin
        out_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op228_write_state11 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_V_V_write = 1'b1;
    end else begin
        out_V_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (exitcond_flatten_fu_421_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (exitcond_flatten_fu_421_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((out_V_V_full_n == 1'b0) & (ap_predicate_op228_write_state11 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((in_V_V_empty_n == 1'b0) & (ap_predicate_op174_read_state9 == 1'b1)) | ((tmp_i_3621_reg_988 == 1'd1) & (in_V_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((out_V_V_full_n == 1'b0) & (ap_predicate_op228_write_state11 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((in_V_V_empty_n == 1'b0) & (ap_predicate_op174_read_state9 == 1'b1)) | ((tmp_i_3621_reg_988 == 1'd1) & (in_V_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((out_V_V_full_n == 1'b0) & (ap_predicate_op228_write_state11 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((in_V_V_empty_n == 1'b0) & (ap_predicate_op174_read_state9 == 1'b1)) | ((tmp_i_3621_reg_988 == 1'd1) & (in_V_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((numReps_out_full_n == 1'b0) | (numReps_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11_pp0_stage0_iter4 = ((out_V_V_full_n == 1'b0) & (ap_predicate_op228_write_state11 == 1'b1));
end

assign ap_block_state7_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter2 = (((in_V_V_empty_n == 1'b0) & (ap_predicate_op174_read_state9 == 1'b1)) | ((tmp_i_3621_reg_988 == 1'd1) & (in_V_V_empty_n == 1'b0)));
end

always @ (*) begin
    ap_condition_428 = ((or_cond_i_reg_1018 == 1'd1) & (tmp_i_3621_reg_988 == 1'd0) & (tmp_2369_fu_783_p1 == 2'd0));
end

always @ (*) begin
    ap_condition_440 = ((or_cond_i_reg_1018 == 1'd1) & (tmp_i_3621_reg_988 == 1'd0) & (tmp_2369_fu_783_p1 == 2'd1));
end

always @ (*) begin
    ap_condition_451 = ((or_cond_i_reg_1018 == 1'd1) & (tmp_i_3621_reg_988 == 1'd0) & (tmp_2369_fu_783_p1 == 2'd2));
end

always @ (*) begin
    ap_condition_462 = ((or_cond_i_reg_1018 == 1'd1) & (tmp_i_3621_reg_988 == 1'd0) & (tmp_2369_fu_783_p1 == 2'd3));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op174_read_state9 = ((or_cond_i_reg_1018 == 1'd1) & (tmp_i_3621_reg_988 == 1'd0));
end

always @ (*) begin
    ap_predicate_op228_write_state11 = ((tmp_i_3621_reg_988_pp0_iter3_reg == 1'd0) & (tmp_170_i_reg_992_pp0_iter3_reg == 1'd1));
end

assign count_simd_fu_535_p2 = (32'd1 + count_simd_1_fu_116);

assign counter_internal_blo_4_fu_701_p2 = (counter_internal_blo_fu_128 + 32'd1);

assign current_block_read_fu_770_p2 = (tmp_fu_764_p2 + tmp_2365_reg_996);

assign current_block_write_1_3615_fu_846_p3 = ((tmp_178_i_fu_840_p2[0:0] === 1'b1) ? 32'd0 : current_block_write_fu_834_p2);

assign current_block_write_2_3616_fu_790_p2 = (current_block_write_5_fu_120 + 32'd1);

assign current_block_write_3_3617_fu_802_p3 = ((tmp_186_i_fu_796_p2[0:0] === 1'b1) ? 32'd0 : current_block_write_2_3616_fu_790_p2);

assign current_block_write_4_3618_fu_810_p3 = ((tmp_185_i_reg_1022[0:0] === 1'b1) ? current_block_write_3_3617_fu_802_p3 : current_block_write_5_fu_120);

assign current_block_write_fu_834_p2 = (current_block_write_5_fu_120 + 32'd1);

assign current_line_3_i_fu_668_p3 = ((tmp_185_i_fu_370_p2[0:0] === 1'b1) ? 32'd0 : grp_fu_364_p2);

assign current_line_in_bloc_fu_529_p2 = (tmp_173_i_fu_521_p3 + count_simd_1_fu_116);

assign exitcond_flatten_fu_421_p2 = ((indvar_flatten_reg_299 == bound_reg_964) ? 1'b1 : 1'b0);

assign grp_fu_364_p2 = (current_line_2_fu_124 + 32'd1);

assign grp_fu_415_p0 = grp_fu_415_p00;

assign grp_fu_415_p00 = numReps_read_reg_954;

assign grp_fu_415_p1 = 44'd3744;

assign i_fu_444_p3 = ((tmp_i_fu_432_p2[0:0] === 1'b1) ? 12'd1 : i_i_op_fu_438_p2);

assign i_i_op_fu_438_p2 = (i_i_reg_310 + 12'd1);

assign indvar_flatten_next_fu_426_p2 = (indvar_flatten_reg_299 + 44'd1);

assign inp_fu_726_p2 = (inp_1_fu_108 + 32'd1);

assign inputBuf_0_V_address0 = tmp_174_i_fu_757_p1;

assign inputBuf_1_V_address0 = tmp_174_i_fu_757_p1;

assign inputBuf_2_V_address0 = tmp_174_i_fu_757_p1;

assign inputBuf_3_V_address0 = tmp_174_i_fu_757_p1;

assign k_x_fu_552_p2 = (k_x_1_fu_112 + 32'd1);

assign k_y_fu_501_p2 = (32'd1 + k_y_1_fu_104);

assign numReps_out_din = numReps_dout;

assign ofm_x_fu_583_p2 = (ofm_x_1_fu_100 + 32'd1);

assign ofm_y_fu_603_p2 = (ofm_y_1_i_fu_96 + 32'd1);

assign or_cond_i_fu_656_p2 = (tmp_183_i_fu_650_p2 & tmp_182_i_fu_644_p2);

assign out_V_V_din = outElem_V_reg_1062;

assign p_i_fu_713_p3 = ((tmp_187_i_fu_707_p2[0:0] === 1'b1) ? 32'd0 : counter_internal_blo_4_fu_701_p2);

assign p_inp_1_i_fu_615_p3 = ((tmp_181_i_fu_609_p2[0:0] === 1'b1) ? 32'd0 : inp_1_fu_108);

assign p_ofm_y_9_i_fu_623_p3 = ((tmp_181_i_fu_609_p2[0:0] === 1'b1) ? 32'd0 : ofm_y_fu_603_p2);

assign read_block_1_fu_676_p3 = ((tmp_185_i_fu_370_p2[0:0] === 1'b1) ? read_block_6_cast_fu_662_p2 : tmp_2363_fu_466_p1);

assign read_block_1_i_mid2_fu_458_p3 = ((tmp_i_reg_978[0:0] === 1'b1) ? 32'd0 : read_block_2_fu_92);

assign read_block_3_cast_i_fu_684_p1 = read_block_1_fu_676_p3;

assign read_block_6_cast_fu_662_p2 = (tmp_2363_fu_466_p1 + 4'd1);

assign read_block_fu_742_p2 = (read_block_1_i_mid2_fu_458_p3 + 32'd1);

assign tmp_169_i_fu_822_p1 = reg_388;

assign tmp_170_i_fu_479_p2 = ((counter_internal_blo_fu_128 < 32'd359) ? 1'b1 : 1'b0);

assign tmp_171_i_fu_515_p2 = (tmp_2368_fu_511_p1 + tmp_2367_fu_507_p1);

assign tmp_173_i_fu_521_p3 = {{tmp_171_i_fu_515_p2}, {2'd0}};

assign tmp_174_i_fu_757_p1 = current_line_in_bloc_reg_1001;

assign tmp_175_i_fu_541_p2 = ((count_simd_fu_535_p2 == 32'd4) ? 1'b1 : 1'b0);

assign tmp_176_i_fu_376_p2 = ((grp_fu_364_p2 == 32'd48) ? 1'b1 : 1'b0);

assign tmp_177_i_fu_558_p2 = ((k_x_fu_552_p2 == 32'd3) ? 1'b1 : 1'b0);

assign tmp_178_i_fu_840_p2 = ((current_block_write_fu_834_p2 == 32'd4) ? 1'b1 : 1'b0);

assign tmp_179_i_fu_569_p2 = ((k_y_fu_501_p2 == 32'd3) ? 1'b1 : 1'b0);

assign tmp_180_i_fu_589_p2 = ((ofm_x_fu_583_p2 == 32'd10) ? 1'b1 : 1'b0);

assign tmp_181_i_fu_609_p2 = ((ofm_y_fu_603_p2 == 32'd10) ? 1'b1 : 1'b0);

assign tmp_182_i_fu_644_p2 = ((counter_internal_blo_fu_128 < 32'd47) ? 1'b1 : 1'b0);

assign tmp_183_i_fu_650_p2 = ((read_block_1_i_mid2_fu_458_p3 < 32'd12) ? 1'b1 : 1'b0);

assign tmp_184_i_fu_775_p1 = reg_388;

assign tmp_185_i_fu_370_p2 = ((grp_fu_364_p2 == 32'd48) ? 1'b1 : 1'b0);

assign tmp_186_i_fu_796_p2 = ((current_block_write_2_3616_fu_790_p2 == 32'd4) ? 1'b1 : 1'b0);

assign tmp_187_i_fu_707_p2 = ((counter_internal_blo_4_fu_701_p2 == 32'd359) ? 1'b1 : 1'b0);

assign tmp_2363_fu_466_p1 = read_block_1_i_mid2_fu_458_p3[3:0];

assign tmp_2364_fu_830_p1 = current_block_write_5_fu_120[1:0];

assign tmp_2365_fu_497_p1 = k_y_1_fu_104[1:0];

assign tmp_2366_fu_753_p1 = current_block_write_5_fu_120[1:0];

assign tmp_2367_fu_507_p1 = k_x_1_fu_112[29:0];

assign tmp_2368_fu_511_p1 = ofm_x_1_fu_100[29:0];

assign tmp_2369_fu_783_p1 = current_block_write_5_fu_120[1:0];

assign tmp_fu_764_p2 = (2'd1 + tmp_2366_fu_753_p1);

assign tmp_i_3621_fu_470_p2 = ((inp_1_fu_108 < 32'd144) ? 1'b1 : 1'b0);

assign tmp_i_fu_432_p2 = ((i_i_reg_310 == 12'd3744) ? 1'b1 : 1'b0);

endmodule //ConvolutionInputGene_5
